Repository EnterpriseDB/docs, pull requests merged in 2023-11, with the labels that each got.

#4963 Update index.mdx
  product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
Labels: deploy

#4966 Added GCP management costs to BigAnimal Management page
  product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
Labels: deploy

#4824 BigAnimal: CLI updates for 3.1
  product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
Labels: deploy

#4900 EDB*Plus - Added windows 2022 and 11 support as per ED-278
  install_template/templates/products/edb*plus/index.njk
  product_docs/docs/edb_plus/41/installing/index.mdx
Labels: deploy

#4849 Node management - Refresh
  product_docs/docs/pgd/5/choosing_server.mdx
  product_docs/docs/pgd/5/consistency/conflicts.mdx
  product_docs/docs/pgd/5/index.mdx
  product_docs/docs/pgd/5/monitoring/sql.mdx
  product_docs/docs/pgd/5/node_management/connections_dsns_and_ssl.mdx
  product_docs/docs/pgd/5/node_management/creating_and_joining.mdx
  product_docs/docs/pgd/5/node_management/decoding_worker.mdx
  product_docs/docs/pgd/5/node_management/groups_and_subgroups.mdx
  product_docs/docs/pgd/5/node_management/heterogeneous_clusters.mdx
  product_docs/docs/pgd/5/node_management/index.mdx
  product_docs/docs/pgd/5/node_management/logical_standby_nodes.mdx
  product_docs/docs/pgd/5/node_management/node_recovery.mdx
  product_docs/docs/pgd/5/node_management/node_types.mdx
  product_docs/docs/pgd/5/node_management/physical_standby_nodes.mdx
  product_docs/docs/pgd/5/node_management/removing_nodes_and_groups.mdx
  product_docs/docs/pgd/5/node_management/replication_slots.mdx
  product_docs/docs/pgd/5/node_management/subscriber_only.mdx
  product_docs/docs/pgd/5/node_management/viewing_topology.mdx
  product_docs/docs/pgd/5/node_management/witness_nodes.mdx
  product_docs/docs/pgd/5/nodes.mdx
  product_docs/docs/pgd/5/postgres-configuration.mdx
  product_docs/docs/pgd/5/reference/functions.mdx
  product_docs/docs/pgd/5/reference/nodes-management-interfaces.mdx
  product_docs/docs/pgd/5/reference/pgd-settings.mdx
Labels: deploy

#4958 Reorganize the EFM virtual IP addresses topic
  product_docs/docs/efm/4/04_configuring_efm/05_using_vip_addresses.mdx
Labels: deploy

#4982 Add test for footnote bug
  advocacy_docs/playground/footnotetest.mdx
Labels: deploy

#4981 Process changes to docs from: repo: EnterpriseDB/cloud-native-postgres ref: refs/tags/v1.21.1
  product_docs/docs/postgres_for_kubernetes/1/applications.mdx
  product_docs/docs/postgres_for_kubernetes/1/backup.mdx
  product_docs/docs/postgres_for_kubernetes/1/backup_barmanobjectstore.mdx
  product_docs/docs/postgres_for_kubernetes/1/backup_volumesnapshot.mdx
  product_docs/docs/postgres_for_kubernetes/1/bootstrap.mdx
  product_docs/docs/postgres_for_kubernetes/1/certificates.mdx
  product_docs/docs/postgres_for_kubernetes/1/cluster_conf.mdx
  product_docs/docs/postgres_for_kubernetes/1/connection_pooling.mdx
  product_docs/docs/postgres_for_kubernetes/1/declarative_role_management.mdx
  product_docs/docs/postgres_for_kubernetes/1/faq.mdx
  product_docs/docs/postgres_for_kubernetes/1/index.mdx
  product_docs/docs/postgres_for_kubernetes/1/installation_upgrade.mdx
  product_docs/docs/postgres_for_kubernetes/1/operator_capability_levels.mdx
  product_docs/docs/postgres_for_kubernetes/1/pg4k.v1.mdx
  product_docs/docs/postgres_for_kubernetes/1/postgis.mdx
  product_docs/docs/postgres_for_kubernetes/1/recovery.mdx
  product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_18_8_rel_notes.mdx
  product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_19_6_rel_notes.mdx
  product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_20_4_rel_notes.mdx
  product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_21_1_rel_notes.mdx
  product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx
  product_docs/docs/postgres_for_kubernetes/1/samples/cluster-example-full.yaml
  product_docs/docs/postgres_for_kubernetes/1/samples/cluster-example-secret.yaml
  product_docs/docs/postgres_for_kubernetes/1/samples/cluster-example-tde.yaml
  product_docs/docs/postgres_for_kubernetes/1/security.mdx
  product_docs/docs/postgres_for_kubernetes/1/storage.mdx
  product_docs/docs/postgres_for_kubernetes/1/wal_archiving.mdx
  scripts/fileProcessor/package-lock.json
  scripts/fileProcessor/package.json
Labels: deploy

#5001 Release: 2023-11-13
  install_template/config.yaml
  product_docs/docs/epas/16/epas_rel_notes/epas16_rel_notes.mdx
  product_docs/docs/mysql_data_adapter/2/installing/linux_x86_64/mysql_debian_10.mdx
  product_docs/docs/pge/16/deploy_options.mdx
  product_docs/docs/pge/16/index.mdx
  product_docs/docs/pge/16/installing/index.mdx
  product_docs/docs/pge/16/installing/linux_x86_64/index.mdx
  product_docs/docs/pge/16/installing/linux_x86_64/pge_centos_7.mdx
  product_docs/docs/pge/16/installing/linux_x86_64/pge_debian_10.mdx
  product_docs/docs/pge/16/installing/linux_x86_64/pge_debian_11.mdx
  product_docs/docs/pge/16/installing/linux_x86_64/pge_other_linux_8.mdx
  product_docs/docs/pge/16/installing/linux_x86_64/pge_other_linux_9.mdx
  product_docs/docs/pge/16/installing/linux_x86_64/pge_rhel_7.mdx
  product_docs/docs/pge/16/installing/linux_x86_64/pge_rhel_8.mdx
  product_docs/docs/pge/16/installing/linux_x86_64/pge_rhel_9.mdx
  product_docs/docs/pge/16/installing/linux_x86_64/pge_ubuntu_18.mdx
  product_docs/docs/pge/16/installing/linux_x86_64/pge_ubuntu_20.mdx
  product_docs/docs/pge/16/installing/linux_x86_64/pge_ubuntu_22.mdx
  product_docs/docs/pge/16/operation.mdx
  product_docs/docs/pge/16/parameters.mdx
  product_docs/docs/pge/16/release_notes/index.mdx
  product_docs/docs/pge/16/release_notes/rel_notes16.1.mdx
  product_docs/docs/pge/16/replication.mdx
  product_docs/docs/pge/16/sql_features/index.mdx
  product_docs/docs/pge/16/sql_features/jdbctxnrollback.mdx
  product_docs/docs/pge/16/sql_features/txnrollback.mdx
  product_docs/docs/pge/16/tde.mdx
Labels: deploy

#4965 Create release notes for PGD 3.7.23 and pglogical 3.7.23
  product_docs/docs/pgd/3.7/bdr/release-notes.mdx
  product_docs/docs/pgd/3.7/pglogical/release-notes.mdx
Labels: upcoming-release

#4979 docs/pgd/fix/BDR-4298/Simplified compatibility chart
  product_docs/docs/pgd/5/index.mdx
Labels: deploy

#4950 bdr_pg_upgrade product doc update
  product_docs/docs/pgd/4/upgrades/bdr_pg_upgrade.mdx
  product_docs/docs/pgd/5/upgrades/bdr_pg_upgrade.mdx
Labels: upcoming-release, do not merge

#5009 Release: 2023-11-14
  product_docs/docs/lasso/4/linux.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.6.0_rel_notes.mdx
  product_docs/docs/migration_portal/4/known_issues_notes.mdx
  product_docs/docs/pgd/3.7/bdr/release-notes.mdx
  product_docs/docs/pgd/3.7/pglogical/release-notes.mdx
  product_docs/docs/pgd/4/rel_notes/index.mdx
  product_docs/docs/pgd/4/rel_notes/pgd_4.3.3_rel_notes.mdx
  product_docs/docs/pgd/4/upgrades/bdr_pg_upgrade.mdx
  product_docs/docs/pgd/5/cli/configuring_cli.mdx
  product_docs/docs/pgd/5/index.mdx
  product_docs/docs/pgd/5/overview/index.mdx
  product_docs/docs/pgd/5/rel_notes/index.mdx
  product_docs/docs/pgd/5/rel_notes/pgd_5.3.0_rel_notes.mdx
  product_docs/docs/pgd/5/upgrades/bdr_pg_upgrade.mdx
  product_docs/docs/pgd/5/upgrades/tpa_overview.mdx
  product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx
  product_docs/docs/pgpool/4/pgpool_rel_notes/443_rel_notes.mdx
  product_docs/docs/pgpool/4/pgpool_rel_notes/index.mdx
  product_docs/docs/tde/15/enabling_tde.mdx
Labels: deploy

#4812 BigAnimal: CLI updates for 3.0
  product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
  product_docs/docs/biganimal/release/reference/cli/using_features.mdx
Labels: deploy

#4933 Update managing_clusters.mdx
  product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
Labels: deploy

#5008 TPA 23.25 content imported
  product_docs/docs/tpa/23/INSTALL-repo.mdx
  product_docs/docs/tpa/23/INSTALL.mdx
  product_docs/docs/tpa/23/ansible-and-sudo.mdx
  product_docs/docs/tpa/23/architecture-PGD-Always-ON.mdx
  product_docs/docs/tpa/23/firstclusterdeployment.mdx
  product_docs/docs/tpa/23/reference/2q_and_edb_repositories.mdx
  product_docs/docs/tpa/23/reference/air-gapped.mdx
  product_docs/docs/tpa/23/reference/git-credentials.mdx
  product_docs/docs/tpa/23/reference/index.mdx
  product_docs/docs/tpa/23/reference/local-repo.mdx
  product_docs/docs/tpa/23/reference/reconciling-local-changes.mdx
  product_docs/docs/tpa/23/tpaexec-upgrade.mdx
Labels: deploy

#5011 Release: 2023-11-15
  install_template/config.yaml
  product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
  product_docs/docs/biganimal/release/reference/cli/using_features.mdx
  product_docs/docs/odbc_connector/16/02_requirements_overview.mdx
  product_docs/docs/odbc_connector/16/index.mdx
  product_docs/docs/odbc_connector/16/installing/index.mdx
  product_docs/docs/odbc_connector/16/installing/linux_ppc64le/odbc_rhel_8.mdx
  product_docs/docs/odbc_connector/16/installing/linux_ppc64le/odbc_rhel_9.mdx
  product_docs/docs/odbc_connector/16/installing/linux_ppc64le/odbc_sles_12.mdx
  product_docs/docs/odbc_connector/16/installing/linux_ppc64le/odbc_sles_15.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_centos_7.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_debian_10.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_debian_11.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_other_linux_8.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_other_linux_9.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_rhel_7.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_rhel_8.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_rhel_9.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_sles_12.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_sles_15.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_ubuntu_18.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_ubuntu_20.mdx
  product_docs/docs/odbc_connector/16/installing/linux_x86_64/odbc_ubuntu_22.mdx
  product_docs/docs/tpa/23/INSTALL-repo.mdx
  product_docs/docs/tpa/23/INSTALL.mdx
  product_docs/docs/tpa/23/ansible-and-sudo.mdx
  product_docs/docs/tpa/23/architecture-PGD-Always-ON.mdx
  product_docs/docs/tpa/23/firstclusterdeployment.mdx
  product_docs/docs/tpa/23/reference/2q_and_edb_repositories.mdx
  product_docs/docs/tpa/23/reference/air-gapped.mdx
  product_docs/docs/tpa/23/reference/git-credentials.mdx
  product_docs/docs/tpa/23/reference/index.mdx
  product_docs/docs/tpa/23/reference/local-repo.mdx
  product_docs/docs/tpa/23/reference/reconciling-local-changes.mdx
  product_docs/docs/tpa/23/rel_notes/index.mdx
  product_docs/docs/tpa/23/rel_notes/tpa_23.25_rel_notes.mdx
  product_docs/docs/tpa/23/tpaexec-upgrade.mdx
Labels: deploy

#4941 PEM - 9.4 release branch
  product_docs/docs/pem/8/pem_rel_notes/865_rel_notes.mdx
  product_docs/docs/pem/9/images/performance_diagnostic_intro.png
  product_docs/docs/pem/9/managing_pem_server.mdx
  product_docs/docs/pem/9/pem_rel_notes/940_rel_notes.mdx
  product_docs/docs/pem/9/pem_rel_notes/index.mdx
  product_docs/docs/pem/9/profiling_workloads/index_advisor.mdx
  product_docs/docs/pem/9/registering_database_server.mdx
  product_docs/docs/pem/9/tuning_performance/performance_diagnostic.mdx
Labels: deploy

#4983 Removed unused images for PgBouncer and PgPool
  product_docs/docs/pgbouncer/1/images/EDB_logo.png
  product_docs/docs/pgbouncer/1/images/add-ons.png
  product_docs/docs/pgbouncer/1/images/edb_logo.svg
  product_docs/docs/pgbouncer/1/images/pg_advanced_server_details.png
  product_docs/docs/pgbouncer/1/images/pgbouncer_configuration_window.png
  product_docs/docs/pgbouncer/1/images/pgbouncer_installation_complete.png
  product_docs/docs/pgbouncer/1/images/pgbouncer_welcome.png
  product_docs/docs/pgbouncer/1/images/ready_to_install.png
  product_docs/docs/pgbouncer/1/images/sb_installation_directory.png
  product_docs/docs/pgbouncer/1/images/sbp_add-on.png
  product_docs/docs/pgbouncer/1/images/sbp_installation_complete.png
  product_docs/docs/pgbouncer/1/images/sbp_language_selection.png
  product_docs/docs/pgbouncer/1/images/sbp_selected_packages.png
  product_docs/docs/pgbouncer/1/images/sbp_start_installation.png
  product_docs/docs/pgbouncer/1/images/sbp_welcome.png
  product_docs/docs/pgbouncer/1/images/uninstall1.png
  product_docs/docs/pgbouncer/1/images/uninstall2.png
  product_docs/docs/pgpool/4/images/EDB_logo.png
  product_docs/docs/pgpool/4/images/edb_logo.svg
  product_docs/docs/pgpool/4/images/installing_pgpoool.png
  product_docs/docs/pgpool/4/images/language_selection.png
  product_docs/docs/pgpool/4/images/pg1.png
  product_docs/docs/pgpool/4/images/pg2.png
  product_docs/docs/pgpool/4/images/pg3.png
  product_docs/docs/pgpool/4/images/pg4.png
  product_docs/docs/pgpool/4/images/pg5.png
  product_docs/docs/pgpool/4/images/pgpool1.png
  product_docs/docs/pgpool/4/images/pgpool2.png
  product_docs/docs/pgpool/4/images/pgpool3.png
  product_docs/docs/pgpool/4/images/pgpool4.png
  product_docs/docs/pgpool/4/images/pgpool5.png
  product_docs/docs/pgpool/4/images/pgpool6.png
  product_docs/docs/pgpool/4/images/pp1.png
  product_docs/docs/pgpool/4/images/pp2.png
  product_docs/docs/pgpool/4/images/pp20.png
  product_docs/docs/pgpool/4/images/welcome.png
Labels: deploy

#4985 Removed unused image files for foreign data wrapper products
  product_docs/docs/hadoop_data_adapter/2/images/EDB_logo.png
  product_docs/docs/hadoop_data_adapter/2/images/ambari_administrative_interface.png
  product_docs/docs/hadoop_data_adapter/2/images/edb_logo.svg
  product_docs/docs/hadoop_data_adapter/2/images/installation_complete.png
  product_docs/docs/hadoop_data_adapter/2/images/installation_wizard_welcome_screen.png
  product_docs/docs/hadoop_data_adapter/2/images/progress_as_the_servers_restart.png
  product_docs/docs/hadoop_data_adapter/2/images/restart_the_server.png
  product_docs/docs/hadoop_data_adapter/2/images/setup_wizard_ready.png
  product_docs/docs/hadoop_data_adapter/2/images/specify_an_installation_directory.png
  product_docs/docs/hadoop_data_adapter/2/images/the_installation_wizard_welcome_screen.png
  product_docs/docs/mongo_data_adapter/5/images/EDB_logo.png
  product_docs/docs/mongo_data_adapter/5/images/ambari_administrative_interface.png
  product_docs/docs/mongo_data_adapter/5/images/edb_logo.svg
  product_docs/docs/mongo_data_adapter/5/images/installation_complete.png
  product_docs/docs/mongo_data_adapter/5/images/installation_wizard_welcome_screen.png
  product_docs/docs/mongo_data_adapter/5/images/progress_as_the_servers_restart.png
  product_docs/docs/mongo_data_adapter/5/images/restart_the_server.png
  product_docs/docs/mongo_data_adapter/5/images/setup_wizard_ready.png
  product_docs/docs/mongo_data_adapter/5/images/specify_an_installation_directory.png
  product_docs/docs/mongo_data_adapter/5/images/the_installation_wizard_welcome_screen.png
  product_docs/docs/mysql_data_adapter/2/images/EDB_logo.png
  product_docs/docs/mysql_data_adapter/2/images/ambari_administrative_interface.png
  product_docs/docs/mysql_data_adapter/2/images/edb_logo.svg
  product_docs/docs/mysql_data_adapter/2/images/progress_as_the_servers_restart.png
  product_docs/docs/mysql_data_adapter/2/images/restart_the_server.png
  product_docs/docs/mysql_data_adapter/2/images/setup_wizard_ready.png
  product_docs/docs/mysql_data_adapter/2/images/specify_an_installation_directory.png
  product_docs/docs/mysql_data_adapter/2/images/the_installation_wizard_welcome_screen.png
Labels: deploy

#4986 Removed unused images from various products
  product_docs/docs/edb_plus/41/images/advanced_server_installation_details.png
  product_docs/docs/edb_plus/41/images/edb_logo.png
  product_docs/docs/edb_plus/41/images/edb_logo.svg
  product_docs/docs/edb_plus/41/images/edb_plus_welcome.png
  product_docs/docs/edb_plus/41/images/installation_complete.png
  product_docs/docs/edb_plus/41/images/installation_directory-new.png
  product_docs/docs/edb_plus/41/images/installation_directory.png
  product_docs/docs/edb_plus/41/images/installation_directory_new.png
  product_docs/docs/edb_plus/41/images/ready_to_install.png
  product_docs/docs/efm/4/efm_deploy_arch/images/EDB_logo.png
  product_docs/docs/efm/4/efm_deploy_arch/images/EFM_PgPool_Azure.png
  product_docs/docs/efm/4/efm_deploy_arch/images/backend_pools.png
  product_docs/docs/efm/4/efm_deploy_arch/images/edb_ha_architecture.png
  product_docs/docs/efm/4/efm_deploy_arch/images/edb_ha_architecture1.png
  product_docs/docs/efm/4/efm_deploy_arch/images/edb_ha_architecture_separate_VM.png
  product_docs/docs/efm/4/efm_deploy_arch/images/edb_logo.svg
  product_docs/docs/efm/4/efm_deploy_arch/images/health_probes.png
  product_docs/docs/efm/4/efm_deploy_arch/images/load_balancing_rules.png
  product_docs/docs/efm/4/efm_deploy_arch/images/placeholder.png
  product_docs/docs/efm/4/efm_deploy_arch/images/rule_port_9898.png
  product_docs/docs/efm/4/efm_deploy_arch/images/rule_port_9999.png
  product_docs/docs/efm/4/images/cascading_replication1.png
  product_docs/docs/efm/4/images/edb_logo.png
  product_docs/docs/efm/4/images/placeholder.png
  product_docs/docs/migration_toolkit/55/images/EDB_logo.png
  product_docs/docs/migration_toolkit/55/images/edb_logo.svg
  product_docs/docs/migration_toolkit/55/images/favicon32.ico
  product_docs/docs/migration_toolkit/55/images/installing_mtk_inst_complete.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_inst_dir.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_license.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_mac_inst_complete.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_mac_inst_dir.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_mac_license.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_mac_setup.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_mac_start_inst.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_categories.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_categories_1.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_categories_3.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_categories_4.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_categories_55.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_download_complete.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_downloading.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_downloading_dir.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_inst_complete.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_password.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_selected_packages.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_selected_packages_1.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_selected_packages_2.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_selected_packages_3.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_selected_packages_55.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_sbp_welcome.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_setup.png
  product_docs/docs/migration_toolkit/55/images/installing_mtk_start_inst.png
  product_docs/docs/migration_toolkit/55/images/placeholder.png
Labels: deploy

#5015 PEM -9.4 fixed release date and added entry to the table
  product_docs/docs/pem/9/pem_rel_notes/940_rel_notes.mdx
  product_docs/docs/pem/9/pem_rel_notes/index.mdx
Labels: deploy

#5012 BDR-4288 - Docs: Improve role management documentation
  product_docs/docs/pgd/5/security/role-management.mdx
Labels: deploy

#5016 Release: 2023-11-16c
  product_docs/docs/pem/9/pem_rel_notes/940_rel_notes.mdx
  product_docs/docs/pem/9/pem_rel_notes/index.mdx
  product_docs/docs/pgd/5/security/role-management.mdx
Labels: deploy

#4833 Initial updates for efm 4.8.
  install_template/templates/products/failover-manager/base.njk
  product_docs/docs/efm/4/04_configuring_efm/01_cluster_properties.mdx
  product_docs/docs/efm/4/04_configuring_efm/02_encrypting_database_password.mdx
  product_docs/docs/efm/4/04_configuring_efm/03_cluster_members.mdx
  product_docs/docs/efm/4/04_configuring_efm/04_extending_efm_permissions.mdx
  product_docs/docs/efm/4/05_using_efm.mdx
  product_docs/docs/efm/4/07_using_efm_utility.mdx
  product_docs/docs/efm/4/08_controlling_efm_service.mdx
  product_docs/docs/efm/4/09_controlling_logging.mdx
  product_docs/docs/efm/4/10_notifications.mdx
  product_docs/docs/efm/4/13_troubleshooting.mdx
  product_docs/docs/efm/4/14_configuring_streaming_replication.mdx
  product_docs/docs/efm/4/efm_quick_start/index.mdx
  product_docs/docs/efm/4/efm_rel_notes/02_efm_48_rel_notes.mdx
  product_docs/docs/efm/4/efm_rel_notes/index.mdx
  product_docs/docs/efm/4/installing/linux_ppc64le/efm_rhel_8.mdx
  product_docs/docs/efm/4/installing/linux_ppc64le/efm_rhel_9.mdx
  product_docs/docs/efm/4/installing/linux_ppc64le/efm_sles_12.mdx
  product_docs/docs/efm/4/installing/linux_ppc64le/efm_sles_15.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_centos_7.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_debian_10.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_debian_11.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_other_linux_8.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_other_linux_9.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_7.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_8.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_9.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_sles_12.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_sles_15.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_18.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_20.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_22.mdx
  product_docs/docs/efm/4/installing/prerequisites.mdx
  product_docs/docs/efm/4/upgrading.mdx
Labels: deploy

#5017 Release/2023-11-16d
  install_template/templates/products/failover-manager/base.njk
  product_docs/docs/efm/4/04_configuring_efm/01_cluster_properties.mdx
  product_docs/docs/efm/4/04_configuring_efm/02_encrypting_database_password.mdx
  product_docs/docs/efm/4/04_configuring_efm/03_cluster_members.mdx
  product_docs/docs/efm/4/04_configuring_efm/04_extending_efm_permissions.mdx
  product_docs/docs/efm/4/05_using_efm.mdx
  product_docs/docs/efm/4/07_using_efm_utility.mdx
  product_docs/docs/efm/4/08_controlling_efm_service.mdx
  product_docs/docs/efm/4/09_controlling_logging.mdx
  product_docs/docs/efm/4/10_notifications.mdx
  product_docs/docs/efm/4/13_troubleshooting.mdx
  product_docs/docs/efm/4/14_configuring_streaming_replication.mdx
  product_docs/docs/efm/4/efm_quick_start/index.mdx
  product_docs/docs/efm/4/efm_rel_notes/02_efm_48_rel_notes.mdx
  product_docs/docs/efm/4/efm_rel_notes/index.mdx
  product_docs/docs/efm/4/installing/linux_ppc64le/efm_rhel_8.mdx
  product_docs/docs/efm/4/installing/linux_ppc64le/efm_rhel_9.mdx
  product_docs/docs/efm/4/installing/linux_ppc64le/efm_sles_12.mdx
  product_docs/docs/efm/4/installing/linux_ppc64le/efm_sles_15.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_centos_7.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_debian_10.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_debian_11.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_other_linux_8.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_other_linux_9.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_7.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_8.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_rhel_9.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_sles_12.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_sles_15.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_18.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_20.mdx
  product_docs/docs/efm/4/installing/linux_x86_64/efm_ubuntu_22.mdx
  product_docs/docs/efm/4/installing/prerequisites.mdx
  product_docs/docs/efm/4/upgrading.mdx
Labels: deploy

#5021 PEM 9.4 - Added curl and libcurl vulnerabilities note
  product_docs/docs/pem/9/pem_rel_notes/940_rel_notes.mdx
Labels: deploy

#5010 EPAS 16 - Replace index advisor with Query advisor
  product_docs/docs/epas/16/epas_rel_notes/epas16_rel_notes.mdx
  product_docs/docs/epas/16/epas_rel_notes/index.mdx
  product_docs/docs/epas/16/managing_performance/02_index_advisor/02_index_advisor_configuration.mdx
  product_docs/docs/epas/16/managing_performance/02_index_advisor/03_using_index_advisor.mdx
  product_docs/docs/epas/16/managing_performance/02_index_advisor/04_reviewing_the_index_advisor_recommendations.mdx
  product_docs/docs/epas/16/managing_performance/02_index_advisor/05_index_advisor_limitations.mdx
  product_docs/docs/epas/16/managing_performance/02_index_advisor/index.mdx
  product_docs/docs/epas/16/managing_performance/02_index_advisor/index_advisor_overview.mdx
  product_docs/docs/epas/16/managing_performance/03_sql_profiler.mdx
  product_docs/docs/epas/16/managing_performance/index.mdx
  product_docs/docs/epas/16/managing_performance/query_advisor.mdx
Labels: deploy

#4968 Migration Portal - 4.7.0 Release branch
  product_docs/docs/migration_portal/4/01_mp_release_notes/10_mp_4.0_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/index.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.1_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.2_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.3_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.4_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.5.1_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.5_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.7.0_rel_notes.mdx
  product_docs/docs/migration_portal/4/03_mp_using_portal/01_mp_overview_home.mdx
  product_docs/docs/migration_portal/4/03_mp_using_portal/02_mp_overview_project.mdx
  product_docs/docs/migration_portal/4/03_mp_using_portal/index.mdx
  product_docs/docs/migration_portal/4/04_mp_migrating_database/02_mp_schema_assessment.mdx
  product_docs/docs/migration_portal/4/images/mp_overview_home.png
  product_docs/docs/migration_portal/4/images/mp_overview_home_1.png
  product_docs/docs/migration_portal/4/images/mp_overview_home_2.png
  product_docs/docs/migration_portal/4/images/mp_overview_home_updated.png
  product_docs/docs/migration_portal/4/images/mp_schema_assessment_new_project_updated.png
  product_docs/docs/migration_portal/4/known_issues_notes.mdx
Labels: deploy

#5030 Release:2023-11-20
  product_docs/docs/migration_portal/4/01_mp_release_notes/10_mp_4.0_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/index.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.1_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.2_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.3_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.4_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.5.1_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.5_rel_notes.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.7.0_rel_notes.mdx
  product_docs/docs/migration_portal/4/03_mp_using_portal/01_mp_overview_home.mdx
  product_docs/docs/migration_portal/4/03_mp_using_portal/02_mp_overview_project.mdx
  product_docs/docs/migration_portal/4/03_mp_using_portal/index.mdx
  product_docs/docs/migration_portal/4/04_mp_migrating_database/02_mp_schema_assessment.mdx
  product_docs/docs/migration_portal/4/images/mp_overview_home.png
  product_docs/docs/migration_portal/4/images/mp_overview_home_1.png
  product_docs/docs/migration_portal/4/images/mp_overview_home_2.png
  product_docs/docs/migration_portal/4/images/mp_overview_home_updated.png
  product_docs/docs/migration_portal/4/images/mp_schema_assessment_new_project_updated.png
  product_docs/docs/migration_portal/4/known_issues_notes.mdx
  product_docs/docs/pem/9/managing_pem_server.mdx
  product_docs/docs/pem/9/pem_rel_notes/940_rel_notes.mdx
  product_docs/docs/pem/9/tuning_performance/performance_diagnostic.mdx
Labels: deploy

#4820 PGD for Kubernetes: copy edit
  product_docs/docs/postgres_distributed_for_kubernetes/1/api_reference.md.in
  product_docs/docs/postgres_distributed_for_kubernetes/1/api_reference.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/architecture.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/backup.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/before_you_start.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/certificates.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/connectivity.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/index.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/installation_upgrade.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/openshift.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/private_registries.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/quickstart.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/recovery.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/samples.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/security.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/ssl_connections.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/use_cases.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/using_pgd.mdx
Labels: deploy

#5029 BigAnimal - Added supported region as per UPM-27095
  product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
Labels: deploy

#4990 Added Release Notes Style Guide
  advocacy_docs/community/contributing/index.mdx
  advocacy_docs/community/contributing/releasenotes-styleguide.mdx
Labels: deploy

#5046 Fix global/local issue to sync with 23.25
  product_docs/docs/pgd/5/quickstart/further_explore_failover.mdx
  product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx
  product_docs/docs/pgd/5/quickstart/quick_start_docker.mdx
  product_docs/docs/pgd/5/quickstart/quick_start_linux.mdx
Labels: deploy

#5047 PEM - 9.4.1 release branch
  product_docs/docs/pem/8/pem_rel_notes/865_rel_notes.mdx
  product_docs/docs/pem/9/pem_rel_notes/941_rel_notes.mdx
  product_docs/docs/pem/9/pem_rel_notes/index.mdx
  product_docs/docs/pem/9/troubleshooting.mdx
Labels: deploy

#5048 Release/2023-11-28
  advocacy_docs/community/contributing/index.mdx
  advocacy_docs/community/contributing/releasenotes-styleguide.mdx
  product_docs/docs/pem/8/pem_rel_notes/865_rel_notes.mdx
  product_docs/docs/pem/9/pem_rel_notes/941_rel_notes.mdx
  product_docs/docs/pem/9/pem_rel_notes/index.mdx
  product_docs/docs/pem/9/troubleshooting.mdx
  product_docs/docs/pgd/5/quickstart/further_explore_failover.mdx
  product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx
  product_docs/docs/pgd/5/quickstart/quick_start_docker.mdx
  product_docs/docs/pgd/5/quickstart/quick_start_linux.mdx
Labels: deploy

#5045 Removed unused image files for EPAS 16
  product_docs/docs/epas/16/images/clear_breakpoints.jpg
  product_docs/docs/epas/16/images/connect_to_epas_server.png
  product_docs/docs/epas/16/images/debugger_window.png
  product_docs/docs/epas/16/images/debugging_called_subprogram.png
  product_docs/docs/epas/16/images/definers_rights_package.png
  product_docs/docs/epas/16/images/edb_logo.png
  product_docs/docs/epas/16/images/edb_logo.svg
  product_docs/docs/epas/16/images/edb_postgres.png
  product_docs/docs/epas/16/images/enterprisedb_technical_alert.png
  product_docs/docs/epas/16/images/epas_linux_advanced_server_service_configuration_file.png
  product_docs/docs/epas/16/images/exiting_from_debugger.png
  product_docs/docs/epas/16/images/image3.png
  product_docs/docs/epas/16/images/local_variables_tab.png
  product_docs/docs/epas/16/images/main_debugger_window.png
  product_docs/docs/epas/16/images/messages_tab.png
  product_docs/docs/epas/16/images/pgAdmin_installation_directory.png
  product_docs/docs/epas/16/images/pgAdmin_welcome.png
  product_docs/docs/epas/16/images/pgadmin4_from_applications_menu.png
  product_docs/docs/epas/16/images/pgadmin_installation.png
  product_docs/docs/epas/16/images/results_tab.png
  product_docs/docs/epas/16/images/setting_global_breakpoint_from_object_menu.png
  product_docs/docs/epas/16/images/stackbuilder_category_AS.png
  product_docs/docs/epas/16/images/stackbuilder_missing_pgAdmin.png
  product_docs/docs/epas/16/images/starting_the_debugger_from_context_menu.png
  product_docs/docs/epas/16/images/starting_the_debugger_from_object_menu.png
  product_docs/docs/epas/16/images/the_stackBuilder_plus_registration_window.png
  product_docs/docs/epas/16/images/toolbar_icons.jpg
  product_docs/docs/epas/16/images/update_notification_service.png
  product_docs/docs/epas/16/images/waiting_invocation_program_debugged.png
Labels: deploy

#5050 PEM - 8.7.0 release branch
  product_docs/docs/pem/8/pem_rel_notes/870_rel_notes.mdx
  product_docs/docs/pem/8/pem_rel_notes/index.mdx
Labels: deploy

#5052 Release: 2023-11-29
  product_docs/docs/epas/16/images/clear_breakpoints.jpg
  product_docs/docs/epas/16/images/connect_to_epas_server.png
  product_docs/docs/epas/16/images/debugger_window.png
  product_docs/docs/epas/16/images/debugging_called_subprogram.png
  product_docs/docs/epas/16/images/definers_rights_package.png
  product_docs/docs/epas/16/images/edb_logo.png
  product_docs/docs/epas/16/images/edb_logo.svg
  product_docs/docs/epas/16/images/edb_postgres.png
  product_docs/docs/epas/16/images/enterprisedb_technical_alert.png
  product_docs/docs/epas/16/images/epas_linux_advanced_server_service_configuration_file.png
  product_docs/docs/epas/16/images/exiting_from_debugger.png
  product_docs/docs/epas/16/images/image3.png
  product_docs/docs/epas/16/images/local_variables_tab.png
  product_docs/docs/epas/16/images/main_debugger_window.png
  product_docs/docs/epas/16/images/messages_tab.png
  product_docs/docs/epas/16/images/pgAdmin_installation_directory.png
  product_docs/docs/epas/16/images/pgAdmin_welcome.png
  product_docs/docs/epas/16/images/pgadmin4_from_applications_menu.png
  product_docs/docs/epas/16/images/pgadmin_installation.png
  product_docs/docs/epas/16/images/results_tab.png
  product_docs/docs/epas/16/images/setting_global_breakpoint_from_object_menu.png
  product_docs/docs/epas/16/images/stackbuilder_category_AS.png
  product_docs/docs/epas/16/images/stackbuilder_missing_pgAdmin.png
  product_docs/docs/epas/16/images/starting_the_debugger_from_context_menu.png
  product_docs/docs/epas/16/images/starting_the_debugger_from_object_menu.png
  product_docs/docs/epas/16/images/the_stackBuilder_plus_registration_window.png
  product_docs/docs/epas/16/images/toolbar_icons.jpg
  product_docs/docs/epas/16/images/update_notification_service.png
  product_docs/docs/epas/16/images/waiting_invocation_program_debugged.png
  product_docs/docs/pem/8/pem_rel_notes/870_rel_notes.mdx
  product_docs/docs/pem/8/pem_rel_notes/index.mdx
Labels: deploy

#5055 Fix for #5037
  advocacy_docs/supported-open-source/postgresql/uninstalling.mdx
Labels: deploy

#5059 Extension updates as per DF-385 request
  advocacy_docs/pg_extensions/extensionrefs.json
  advocacy_docs/pg_extensions/index.mdx
Labels: deploy

#5062 TPA 23.26 updates
  product_docs/docs/tpa/23/platform-bare.mdx
  product_docs/docs/tpa/23/reference/bdr.mdx
  product_docs/docs/tpa/23/reference/reconciling-local-changes.mdx
  product_docs/docs/tpa/23/reference/tpaexec-deprovision.mdx
  product_docs/docs/tpa/23/tpaexec-configure.mdx
Labels: deploy
