Repository EnterpriseDB/docs, pull requests merged in 2023-08, with the labels that each got.

#4539 PEM - SQL Profiler fix as per DF-353
  product_docs/docs/pem/9/profiling_workloads/installing_sql_profiler.mdx
Labels: deploy

#4534 Add new page on updating HTTPD
  product_docs/docs/pem/9/images/stackbuilder_pemhttpd.png
  product_docs/docs/pem/9/upgrading/index.mdx
  product_docs/docs/pem/9/upgrading/upgrading_httpd.mdx
Labels: deploy

#4549 pgBackRest 2.47 was released
  advocacy_docs/supported-open-source/pgbackrest/06-use_case_1.mdx
  advocacy_docs/supported-open-source/pgbackrest/99-faq.mdx
  advocacy_docs/supported-open-source/pgbackrest/index.mdx
Labels: deploy

#4442 Normalizing upgrade instructions and reducing need for edits when platforms are added
  product_docs/docs/hadoop_data_adapter/2/upgrading.mdx
  product_docs/docs/jdbc_connector/42.5.4.1/installing/upgrading.mdx
  product_docs/docs/migration_toolkit/55/upgrading.mdx
  product_docs/docs/mongo_data_adapter/5/upgrading.mdx
  product_docs/docs/mysql_data_adapter/2/upgrading.mdx
  product_docs/docs/ocl_connector/15/installing/upgrading.mdx
  product_docs/docs/odbc_connector/13/installing/upgrading.mdx
  product_docs/docs/pgbouncer/1/upgrading.mdx
  product_docs/docs/pgpool/4/installing/upgrading.mdx
  product_docs/docs/pgpool/4/installing_extensions/upgrading_extensions.mdx
Labels: deploy

#4502 Revised upgrade language to be more consistent with other product
  product_docs/docs/pem/9/upgrading/upgrading_pem_installation/upgrading_pem_installation_linux_rpm.mdx
Labels: deploy

#4474 Switched in grey crosses for No
  advocacy_docs/pg_extensions/extensionrefs.json
  advocacy_docs/pg_extensions/index.mdx
  tools/user/import/extensions/exsp.js
Labels: deploy

#4552 Edits to PR4505
  product_docs/docs/epas/15/database_administration/10_edb_resource_manager/dirty_buffer_throttling.mdx
  product_docs/docs/epas/15/database_administration/10_edb_resource_manager/index.mdx
  product_docs/docs/epas/15/epas_security_guide/02_protecting_against_sql_injection_attacks/index.mdx
  product_docs/docs/epas/15/epas_security_guide/04_sslutils.mdx
  product_docs/docs/epas/15/epas_security_guide/05_data_redaction/index.mdx
  product_docs/docs/epas/15/fundamentals/epas_fundamentals/benefits_epas.mdx
  product_docs/docs/epas/15/fundamentals/epas_fundamentals/index.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_about_the_examples_used_in_this_guide.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_conventions.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_sql_tutorial/01_sample_database/01_sample_database_installation.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_sql_tutorial/05_joins_between_tables.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_sql_tutorial/index.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/03_advanced_concepts/02_foreign_keys.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/03_advanced_concepts/03_the_rownum_pseudo_column.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/03_advanced_concepts/04_synonyms.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/03_advanced_concepts/05_hierarchical_queries/02_selecting_the_root_nodes.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/03_advanced_concepts/05_hierarchical_queries/06_retrieving_the_root_node_with_connect_by_root.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/03_advanced_concepts/06_multidimensional_analysis/03_grouping_sets_extension.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/03_examples_used.mdx
  product_docs/docs/epas/15/index.mdx
  product_docs/docs/epas/15/installing/linux_install_details/rpm_packages.mdx
  product_docs/docs/epas/15/planning/configuration_mode.mdx
  product_docs/docs/epas/15/planning/planning_prerequisites/epas_requirements/index.mdx
  product_docs/docs/epas/15/reference/database_administrator_reference/02_summary_of_configuration_parameters.mdx
Labels: deploy

#4560 Restaging 52
  product_docs/docs/pgd/5/cli/command_ref/pgd_verify-settings.mdx
  product_docs/docs/pgd/5/index.mdx
  product_docs/docs/pgd/5/parallelapply.mdx
  product_docs/docs/pgd/5/reference/autopartition.mdx
  product_docs/docs/pgd/5/reference/catalogs-visible.mdx
  product_docs/docs/pgd/5/reference/index.json
  product_docs/docs/pgd/5/reference/index.mdx
  product_docs/docs/pgd/5/reference/index.mdx.src
  product_docs/docs/pgd/5/rel_notes/index.mdx
  product_docs/docs/pgd/5/rel_notes/pgd_5.2.0_rel_notes.mdx
  product_docs/docs/pgd/5/routing/installing_proxy.mdx
  product_docs/docs/pgd/5/routing/proxy.mdx
  product_docs/docs/pgd/5/scaling.mdx
  product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx
  tools/automation/generators/refbuilder/refbuilder.js
Labels: deploy

#4554 Edits for the Managing performance branch
  product_docs/docs/epas/15/managing_performance/02_index_advisor/02_index_advisor_configuration.mdx
  product_docs/docs/epas/15/managing_performance/02_index_advisor/03_using_index_advisor.mdx
  product_docs/docs/epas/15/managing_performance/02_index_advisor/04_reviewing_the_index_advisor_recommendations.mdx
  product_docs/docs/epas/15/managing_performance/02_index_advisor/05_index_advisor_limitations.mdx
  product_docs/docs/epas/15/managing_performance/02_index_advisor/index.mdx
  product_docs/docs/epas/15/managing_performance/03_sql_profiler.mdx
  product_docs/docs/epas/15/managing_performance/04_dynamic_runtime_instrumentation_tools_architecture_DRITA/index.mdx
  product_docs/docs/epas/15/managing_performance/04_dynamic_runtime_instrumentation_tools_architecture_DRITA/performance_tuning_recommendations.mdx
  product_docs/docs/epas/15/managing_performance/04_dynamic_runtime_instrumentation_tools_architecture_DRITA/simulating_statspack_reports.mdx
  product_docs/docs/epas/15/managing_performance/04_dynamic_runtime_instrumentation_tools_architecture_DRITA/taking_a_snapshot.mdx
  product_docs/docs/epas/15/managing_performance/04_dynamic_runtime_instrumentation_tools_architecture_DRITA/using_drita_functions.mdx
  product_docs/docs/epas/15/managing_performance/index.mdx
  product_docs/docs/epas/15/managing_performance/using_dynatune.mdx
Labels: deploy

#4469 Tech Partner DBeaver Guide Updates
  advocacy_docs/partner_docs/DBeaverPRO/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/DBeaverPRO/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/DBeaverPRO/04-ConfiguringDBeaverPRO.mdx
  advocacy_docs/partner_docs/DBeaverPRO/05-UsingDBeaverPRO.mdx
  advocacy_docs/partner_docs/DBeaverPRO/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/DBeaverPRO/07-SupportandLogging.mdx
  advocacy_docs/partner_docs/DBeaverPRO/Images/CompareMigrateSchema.png
  advocacy_docs/partner_docs/DBeaverPRO/Images/DBeaverErrorLogs.png
  advocacy_docs/partner_docs/DBeaverPRO/Images/DBeaverLogViewer.png
  advocacy_docs/partner_docs/DBeaverPRO/Images/EPASConnectionSettings.png
  advocacy_docs/partner_docs/DBeaverPRO/Images/EPASDatabaseConfiguration.png
  advocacy_docs/partner_docs/DBeaverPRO/Images/EPASTestConnection.png
  advocacy_docs/partner_docs/DBeaverPRO/Images/ExtendedTestConnection.png
  advocacy_docs/partner_docs/DBeaverPRO/Images/JDBCConnection.png
  advocacy_docs/partner_docs/DBeaverPRO/Images/SameSchemaCompareResults.png
  advocacy_docs/partner_docs/DBeaverPRO/Images/SchemaCompareDiffResults.png
  advocacy_docs/partner_docs/DBeaverPRO/Images/SchemaCompareSettings.png
  advocacy_docs/partner_docs/DBeaverPRO/Images/SchemasToCompare.png
  advocacy_docs/partner_docs/DBeaverPRO/Images/SelectTargetSourceforCompare.png
Labels: deploy

#4564 BigAnimal: GCP private endpoints
  product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/01_connecting_from_azure/index.mdx
  product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/02_connecting_from_aws/index.mdx
  product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_a_client.mdx
  product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_gcp/index.mdx
Labels: deploy

#4580 Use correct path for PDF noindex headers
  gatsby-config.js
Labels: deploy

#4571 BigAnimal: auto tuning support
  advocacy_docs/pg_extensions/pg_tuner/using.mdx
Labels: deploy

#4559 Clarify for RHEL-like systems
  product_docs/docs/pem/9/upgrading/upgrading_httpd.mdx
Labels: deploy

#4527 Edits for topics in the Installing and Upgrading branches
  product_docs/docs/epas/15/fundamentals/epas_fundamentals/benefits_epas.mdx
  product_docs/docs/epas/15/installing/linux_install_details/index.mdx
  product_docs/docs/epas/15/installing/linux_install_details/installing_epas_using_local_repository.mdx
  product_docs/docs/epas/15/installing/linux_install_details/managing_an_advanced_server_installation.mdx
  product_docs/docs/epas/15/installing/linux_install_details/managing_an_advanced_server_installation/configuring_a_package_installation.mdx
  product_docs/docs/epas/15/installing/linux_install_details/managing_an_advanced_server_installation/connecting_to_epas.mdx
  product_docs/docs/epas/15/installing/linux_install_details/managing_an_advanced_server_installation/index.mdx
  product_docs/docs/epas/15/installing/linux_install_details/managing_an_advanced_server_installation/modifying_the_data_directory_location.mdx
  product_docs/docs/epas/15/installing/linux_install_details/managing_an_advanced_server_installation/specifying_cluster_options.mdx
  product_docs/docs/epas/15/installing/linux_install_details/managing_an_advanced_server_installation/starting_and_stopping_services.mdx
  product_docs/docs/epas/15/installing/linux_install_details/managing_an_advanced_server_installation/starting_multiple_postmasters.mdx
  product_docs/docs/epas/15/installing/linux_install_details/rpm_packages.mdx
  product_docs/docs/epas/15/installing/linux_install_details/updating_an_rpm_installation.mdx
  product_docs/docs/epas/15/installing/linux_ppc64le/epas_rhel_7.mdx
  product_docs/docs/epas/15/installing/linux_ppc64le/epas_rhel_8.mdx
  product_docs/docs/epas/15/installing/linux_ppc64le/epas_rhel_9.mdx
  product_docs/docs/epas/15/installing/linux_ppc64le/epas_sles_12.mdx
  product_docs/docs/epas/15/installing/linux_ppc64le/epas_sles_15.mdx
  product_docs/docs/epas/15/installing/linux_x86_64/epas_centos_7.mdx
  product_docs/docs/epas/15/installing/linux_x86_64/epas_other_linux_8.mdx
  product_docs/docs/epas/15/installing/linux_x86_64/epas_other_linux_9.mdx
  product_docs/docs/epas/15/installing/linux_x86_64/epas_rhel_7.mdx
  product_docs/docs/epas/15/installing/linux_x86_64/epas_rhel_8.mdx
  product_docs/docs/epas/15/installing/linux_x86_64/epas_rhel_9.mdx
  product_docs/docs/epas/15/installing/linux_x86_64/epas_sles_12.mdx
  product_docs/docs/epas/15/installing/linux_x86_64/epas_sles_15.mdx
  product_docs/docs/epas/15/installing/uninstalling/linux_uninstall.mdx
  product_docs/docs/epas/15/installing/uninstalling/windows_uninstall.mdx
  product_docs/docs/epas/15/installing/windows/index.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/index.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/invoking_the_graphical_installer_from_the_command_line/performing_an_installation_with_limited_privileges.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/invoking_the_graphical_installer_from_the_command_line/performing_an_unattended_installation.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/performing_a_graphical_installation_on_windows.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/setting_cluster_preferences.mdx
  product_docs/docs/epas/15/installing/windows/managing_an_advanced_server_installation/configuring_epas.mdx
  product_docs/docs/epas/15/installing/windows/managing_an_advanced_server_installation/controlling_server_startup_behavior_on_windows.mdx
  product_docs/docs/epas/15/installing/windows/managing_an_advanced_server_installation/index.mdx
  product_docs/docs/epas/15/installing/windows/managing_an_advanced_server_installation/starting_and_stopping_epas.mdx
  product_docs/docs/epas/15/installing/windows/managing_an_advanced_server_installation/using_the_windows_services_applet.mdx
  product_docs/docs/epas/15/upgrading/03_limitations.mdx
  product_docs/docs/epas/15/upgrading/04_upgrading_an_installation_with_pg_upgrade/03_upgrading_to_advanced_server.mdx
  product_docs/docs/epas/15/upgrading/04_upgrading_an_installation_with_pg_upgrade/how_pg_upgrade_works.mdx
Labels: deploy

#4597 dirty links change to make link to index work
  product_docs/docs/pgd/5/routing/installing_proxy.mdx
Labels: deploy

#4581 BigAnimal: high availability cluster types name change
  product_docs/docs/biganimal/release/getting_started/creating_a_cluster/creating_an_eha_cluster.mdx
  product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
  product_docs/docs/biganimal/release/index.mdx
  product_docs/docs/biganimal/release/overview/02_high_availability.mdx
  product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
  product_docs/docs/biganimal/release/overview/index.mdx
  product_docs/docs/biganimal/release/overview/poolers.mdx
  product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
  product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx
Labels: deploy

#4584 BigAnimal: updates to PGD CLI commands
  product_docs/docs/biganimal/release/overview/02_high_availability.mdx
  product_docs/docs/biganimal/release/reference/cli/index.mdx
  product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
  product_docs/docs/biganimal/release/reference/cli/using_features.mdx
Labels: deploy

#4602 BigAnimal: link to edb-psql doc
  product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/connecting_from_a_client.mdx
Labels: deploy

#4629 Initial release of security section in documentation w/ a few CVEs
  advocacy_docs/security/advisories/cve.mdx.template
  advocacy_docs/security/advisories/cve20074639.mdx
  advocacy_docs/security/advisories/cve201910128.mdx
  advocacy_docs/security/advisories/cve202331043.mdx
  advocacy_docs/security/advisories/index.mdx
  advocacy_docs/security/index.mdx
  advocacy_docs/security/vulnerability-disclosure-policy.mdx
  src/components/footer.js
  src/templates/learn-doc.js
Labels: deploy

#4543 Edits to Veritas doc
  advocacy_docs/partner_docs/VeritasNetBackupforPostgreSQL/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/VeritasNetBackupforPostgreSQL/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/VeritasNetBackupforPostgreSQL/04-ConfiguringVeritasNetBackupforPostgreSQL.mdx
  advocacy_docs/partner_docs/VeritasNetBackupforPostgreSQL/05-UsingVeritasNetBackupForPostgreSQL.mdx
  advocacy_docs/partner_docs/VeritasNetBackupforPostgreSQL/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/VeritasNetBackupforPostgreSQL/index.mdx
Labels: waiting-on

#4526 edits to sib visions partner doc
  advocacy_docs/partner_docs/SIBVisionsVisionX/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/SIBVisionsVisionX/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/SIBVisionsVisionX/04-ConfiguringSIBVisionsVisionX.mdx
  advocacy_docs/partner_docs/SIBVisionsVisionX/05-UsingSIBVisionsVisionX.mdx
  advocacy_docs/partner_docs/SIBVisionsVisionX/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/SIBVisionsVisionX/index.mdx
Labels: deploy, waiting-on

#4525 Edits to Repostor partner doc
  advocacy_docs/partner_docs/RepostorDataProtectorforPostgreSQL/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/RepostorDataProtectorforPostgreSQL/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/RepostorDataProtectorforPostgreSQL/04-ConfiguringRepostorDataProtectorforPostgreSQL.mdx
  advocacy_docs/partner_docs/RepostorDataProtectorforPostgreSQL/05-UsingRepostorDataProtectorforPostgreSQL.mdx
  advocacy_docs/partner_docs/RepostorDataProtectorforPostgreSQL/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/RepostorDataProtectorforPostgreSQL/index.mdx
Labels: deploy, waiting-on

#4519 Edits to Quest Toad Edge partner doc
  advocacy_docs/partner_docs/QuestToadEdge/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/QuestToadEdge/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/QuestToadEdge/04-ConfiguringQuestToadEdge.mdx
  advocacy_docs/partner_docs/QuestToadEdge/05-UsingQuestToadEdge.mdx
  advocacy_docs/partner_docs/QuestToadEdge/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/QuestToadEdge/index.mdx
Labels: deploy, waiting-on

#4504 Pure Storage edits
  advocacy_docs/partner_docs/PureStorageFlashArray/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/PureStorageFlashArray/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/PureStorageFlashArray/04-ConfiguringPureStorageFlashArray.mdx
  advocacy_docs/partner_docs/PureStorageFlashArray/05-UsingPureStorageFlashArray.mdx
  advocacy_docs/partner_docs/PureStorageFlashArray/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/PureStorageFlashArray/07-SupportandLoggingDetails.mdx
  advocacy_docs/partner_docs/PureStorageFlashArray/index.mdx
Labels: deploy, waiting-on

#4503 Major cleanup to Precisely Connect CDC partner content
  advocacy_docs/partner_docs/PreciselyConnectCDC/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/PreciselyConnectCDC/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/PreciselyConnectCDC/04-Configuratingpreciselyconnectcdc.mdx
  advocacy_docs/partner_docs/PreciselyConnectCDC/05-Usingpreciselyconnectcdc.mdx
  advocacy_docs/partner_docs/PreciselyConnectCDC/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/PreciselyConnectCDC/07-Support.mdx
  advocacy_docs/partner_docs/PreciselyConnectCDC/index.mdx
Labels: deploy, waiting-on

#4495 Edits to Nutanix doc
  advocacy_docs/partner_docs/NutanixAHV/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/NutanixAHV/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/NutanixAHV/04-ConfiguringNutanixAHV.mdx
  advocacy_docs/partner_docs/NutanixAHV/05-UsingNutanixAHV.mdx
  advocacy_docs/partner_docs/NutanixAHV/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/NutanixAHV/07-Support.mdx
  advocacy_docs/partner_docs/NutanixAHV/index.mdx
Labels: deploy, waiting-on

#4493 Liquibase Pro edits
  advocacy_docs/partner_docs/LiquibasePro/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/LiquibasePro/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/LiquibasePro/04-ConfiguringLiquibasePro.mdx
  advocacy_docs/partner_docs/LiquibasePro/05-UsingLiquibasePro.mdx
  advocacy_docs/partner_docs/LiquibasePro/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/LiquibasePro/07-Appendix.mdx
  advocacy_docs/partner_docs/LiquibasePro/index.mdx
Labels: deploy, waiting-on

#4489 Edits to Imperva partner doc
  advocacy_docs/partner_docs/ImpervaDataSecurityFabric/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/ImpervaDataSecurityFabric/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/ImpervaDataSecurityFabric/04-ConfiguringImpervaDataSecurityFabric.mdx
  advocacy_docs/partner_docs/ImpervaDataSecurityFabric/05-UsingImpervaDataSecurityFabric.mdx
  advocacy_docs/partner_docs/ImpervaDataSecurityFabric/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/ImpervaDataSecurityFabric/07-Support.mdx
  advocacy_docs/partner_docs/ImpervaDataSecurityFabric/index.mdx
Labels: deploy, waiting-on

#4479 First edit of Hashicorp/Vault
  advocacy_docs/partner_docs/HashicorpVault/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/HashicorpVault/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/HashicorpVault/04-ConfiguringHashicorpVault.mdx
  advocacy_docs/partner_docs/HashicorpVault/05-UsingHashicorpVault.mdx
  advocacy_docs/partner_docs/HashicorpVault/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/HashicorpVault/07-SupportandLogging.mdx
  advocacy_docs/partner_docs/HashicorpVault/index.mdx
Labels: deploy, waiting-on

#4541 Edits to Thales CipherTrust content
  advocacy_docs/partner_docs/ThalesCipherTrustManager/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/04-ConfiguringThalesCipherTrustManager.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/05-UsingThalesCipherTrustManager.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/07-SupportandLogging.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/index.mdx
Labels: deploy, waiting-on

#4478 Docs/esriarcgisenterprise edits
  advocacy_docs/partner_docs/EsriArcGISEnterprise/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/EsriArcGISProandEsriArcGISEnterprise/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/EsriArcGISProandEsriArcGISEnterprise/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/EsriArcGISProandEsriArcGISEnterprise/04-ConfiguringEsriArcGISProandEsriArcGISEnterprise.mdx
  advocacy_docs/partner_docs/EsriArcGISProandEsriArcGISEnterprise/05-UsingEsriArcGISProandEsriArcGISEnterprise.mdx
  advocacy_docs/partner_docs/EsriArcGISProandEsriArcGISEnterprise/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/EsriArcGISProandEsriArcGISEnterprise/index.mdx
Labels: deploy, waiting-on

#4654 EPAS: front matter error message on bottom of page
  product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_sql/22_create_directory.mdx
  product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_sql/23_create_function.mdx
Labels: deploy

#4422 First pass at Chemaxon content
  advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/04-Configuration.mdx
  advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/05-Using.mdx
  advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/ChemaxonJChemPostgreSQLCartridge/index.mdx
Labels: deploy, waiting-on

#4634 Edits to installs and consistent nomenclature for versions
  product_docs/docs/epas/15/application_programming/12_debugger/configuring_debugger.mdx
  product_docs/docs/epas/15/application_programming/ecpgplus_guide/installing_ecpgplus.mdx
  product_docs/docs/epas/15/database_administration/14_edb_clone_schema/setting_up_edb_clone_schema.mdx
  product_docs/docs/epas/15/epas_security_guide/02_protecting_against_sql_injection_attacks/02_configuring_sql_protect.mdx
  product_docs/docs/epas/15/epas_security_guide/04_sslutils.mdx
  product_docs/docs/epas/15/epas_security_guide/tde_feature.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_conventions.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/03_examples_used.mdx
  product_docs/docs/epas/15/installing/uninstalling/linux_uninstall.mdx
  product_docs/docs/epas/15/installing/uninstalling/windows_uninstall.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/index.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/invoking_the_graphical_installer_from_the_command_line/index.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/invoking_the_graphical_installer_from_the_command_line/performing_an_installation_with_limited_privileges.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/invoking_the_graphical_installer_from_the_command_line/performing_an_unattended_installation.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/invoking_the_graphical_installer_from_the_command_line/reference_command_line_options.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/performing_a_graphical_installation_on_windows.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/using_stackbuilder_plus.mdx
  product_docs/docs/epas/15/installing/windows/managing_an_advanced_server_installation/configuring_epas.mdx
  product_docs/docs/epas/15/managing_performance/02_index_advisor/02_index_advisor_configuration.mdx
  product_docs/docs/epas/15/reference/database_administrator_reference/01_index_advisor_components.mdx
Labels: deploy

#4662 Doc/pgd/fix/painconfig
  product_docs/docs/pgd/3.7/bdr/configuration.mdx
  product_docs/docs/pgd/4/bdr/configuration.mdx
Labels: deploy

#4437 Edits to Cohesity doc
  advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/04-ConfiguringCohesityDataProtectforPostgreSQL.mdx
  advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/05-UsingCohesityDataProtectforPostgreSQL.mdx
  advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/CohesityDataProtectforPostgreSQL/index.mdx
Labels: deploy, waiting-on

#4393 Sample edits for HPE
  advocacy_docs/partner_docs/HPE/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/HPE/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/HPE/04-ConfiguringHPEGreenlake.mdx
  advocacy_docs/partner_docs/HPE/05-UsingHPEGreenlake.mdx
  advocacy_docs/partner_docs/HPE/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/HPE/07-SupportandLogging.mdx
  advocacy_docs/partner_docs/HPE/index.mdx
Labels: deploy, waiting-on

#4672 Faster builds: bigger machines, smaller tables
  .github/workflows/deploy-develop.yml
  .github/workflows/deploy-draft.yml
  .github/workflows/deploy-main.yml
  src/constants/gatsby-utils.js
Labels: deploy

#3008 Outline strategy for forking product docs without losing history
  docs/agreements/product-version-fork.md
Labels: docs-on-docs

#4659 OCL Connector: 15.2.0.4 release
  product_docs/docs/ocl_connector/15/ocl_rel_notes/15.2.0.4_ocl_release_notes.mdx
  product_docs/docs/ocl_connector/15/ocl_rel_notes/index.mdx
Labels: upcoming-release, deploy

#4681 BigAnimal: removed duplicated sections
  product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
Labels: deploy

#4639 EPAS 15 - Log file fix as per DB-2428
  product_docs/docs/epas/11/installing/linux_install_details/component_locations.mdx
  product_docs/docs/epas/12/installing/linux_install_details/component_locations.mdx
  product_docs/docs/epas/13/installing/linux_install_details/component_locations.mdx
  product_docs/docs/epas/14/installing/linux_install_details/component_locations.mdx
  product_docs/docs/epas/15/installing/linux_install_details/component_locations.mdx
Labels: deploy

#4694 Replication Server: adding driver step to upgrade instructions
  product_docs/docs/eprs/7/installing/upgrading_replication_server/index.mdx
  product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_linux.mdx
  product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_gui_installer.mdx
  product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_xdb_rpm_package.mdx
Labels: deploy

#4697 Homepage: What's new - epas reorg
  src/pages/index.js
Labels: deploy

#4693 PGD doc changes related to BA PGD GQ
  product_docs/docs/pgd/5/deployments.mdx
  product_docs/docs/pgd/5/quickstart/index.mdx
Labels: deploy

#4695 OCL Connector: libpq requirement
  product_docs/docs/ocl_connector/15/03_libpq_compatibility.mdx
  product_docs/docs/ocl_connector/15/installing/upgrading.mdx
  product_docs/docs/ocl_connector/15/ocl_rel_notes/15.2.0.4_ocl_release_notes.mdx
Labels: deploy

#4704 Updates with final CVEs
  advocacy_docs/security/advisories/cve20074639.mdx
  advocacy_docs/security/advisories/cve201910128.mdx
  advocacy_docs/security/advisories/cve202331043.mdx
  advocacy_docs/security/advisories/cve202341113.mdx
  advocacy_docs/security/advisories/cve202341114.mdx
  advocacy_docs/security/advisories/cve202341115.mdx
  advocacy_docs/security/advisories/cve202341116.mdx
  advocacy_docs/security/advisories/cve202341117.mdx
  advocacy_docs/security/advisories/cve202341118.mdx
  advocacy_docs/security/advisories/cve202341119.mdx
  advocacy_docs/security/advisories/cve202341120.mdx
  advocacy_docs/security/advisories/index.mdx
  advocacy_docs/security/index.mdx
Labels: deploy

#4706 Replication Server: fixing links
  product_docs/docs/eprs/7/installing/upgrading_replication_server/index.mdx
  product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_linux.mdx
  product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_gui_installer.mdx
  product_docs/docs/eprs/7/installing/upgrading_replication_server/upgrading_with_xdb_rpm_package.mdx
Labels: deploy

#4708 PGE and EPAS: 15.4 rel notes
  product_docs/docs/epas/15/epas_rel_notes/epas15_4_0_rel_notes.mdx
  product_docs/docs/pge/15/release_notes/index.mdx
  product_docs/docs/pge/15/release_notes/rel_notes15.4.mdx
Labels: deploy

#4618 BigAnimal: PGD GA
  product_docs/docs/biganimal/release/getting_started/creating_a_cluster/creating_an_eha_cluster.mdx
  product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
  product_docs/docs/biganimal/release/overview/02_high_availability.mdx
  product_docs/docs/biganimal/release/overview/poolers.mdx
  product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
  product_docs/docs/biganimal/release/reference/cli/managing_clusters.mdx
  product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx
  product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx
  product_docs/docs/pgd/5/deployments.mdx
  product_docs/docs/pgd/5/quickstart/index.mdx
Labels: upcoming-release, deploy

#4691 Light edits to reorged EPAS content
  product_docs/docs/epas/15/application_programming/ecpgplus_guide/installing_ecpgplus.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_spl/02_spl_programs/04_procedures_overview/01_creating_a_procedure.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_spl/02_spl_programs/06_procedure_and_function_parameters/declaring_parameters.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_spl/06_transaction_control/about_transactions.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_spl/10_collections/about_collections.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_spl/12_working_with_collections/03_using_the_forall_statement.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_spl/13_triggers/02_types_of_triggers.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_spl/13_triggers/07_trigger_examples/06_compound_trigger.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_spl/15_object_types_and_objects/01_basic_object_concepts/02_methods.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_spl/15_object_types_and_objects/01_basic_object_concepts/index.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_spl/15_object_types_and_objects/03_creating_object_types/03_constructor_methods.mdx
  product_docs/docs/epas/15/application_programming/optimizing_code/05_optimizer_hints/about_optimizer_hints.mdx
Labels: deploy

#4682 Speed up Netlify deploys
  gatsby-node.js
  src/components/feedback-dropdown.js
  src/components/footer.js
  src/components/layout.js
  src/components/left-nav.js
  src/components/link.js
  src/components/prev-next.js
  src/constants/gatsby-utils.js
  src/constants/utils.js
  src/templates/doc.js
  src/templates/learn-doc.js
Labels: deploy

#4655 Update guidance for upgrading PGD from 3.7 to 5
  product_docs/docs/pgd/5/upgrades/upgrade_paths.mdx
Labels: deploy

#4703 BigAnimal: choosing config
  product_docs/docs/biganimal/release/overview/02_high_availability.mdx
Labels: deploy

#4733 Update README.md
  README.md
Labels: docs-on-docs

#4673 PEM 9.3 - Release branch
  product_docs/docs/pem/9/images/alert_copy.png
  product_docs/docs/pem/9/images/alert_history_report_general.png
  product_docs/docs/pem/9/images/alerting_manage_alerts.png
  product_docs/docs/pem/9/images/default_email_template.png
  product_docs/docs/pem/9/images/email_template_edit.png
  product_docs/docs/pem/9/images/email_template_restore.png
  product_docs/docs/pem/9/images/pem_management_menu.png
  product_docs/docs/pem/9/installing/configuring_the_pem_server_on_linux.mdx
  product_docs/docs/pem/9/monitoring_performance/alerts.mdx
  product_docs/docs/pem/9/monitoring_performance/notifications.mdx
  product_docs/docs/pem/9/pem_rel_notes/930_rel_notes.mdx
  product_docs/docs/pem/9/pem_rel_notes/index.mdx
  product_docs/docs/pem/9/pem_web_interface.mdx
  product_docs/docs/pem/9/reports.mdx
Labels: upcoming-release, deploy

#4729 some cleanup to the OCL doc
  product_docs/docs/ocl_connector/15/02_supported_platforms.mdx
  product_docs/docs/ocl_connector/15/03_libpq_compatibility.mdx
  product_docs/docs/ocl_connector/15/04_open_client_library/02_forming_a_connection_string.mdx
  product_docs/docs/ocl_connector/15/04_open_client_library/03_compiling_and_linking_a_program.mdx
  product_docs/docs/ocl_connector/15/04_open_client_library/04_ref_cursor_support.mdx
  product_docs/docs/ocl_connector/15/04_open_client_library/05_ocl_function_reference.mdx
  product_docs/docs/ocl_connector/15/04_open_client_library/06_ocl_error_codes_reference.mdx
  product_docs/docs/ocl_connector/15/04_open_client_library/08_otl_support.mdx
  product_docs/docs/ocl_connector/15/05_generating_the_ocl_trace.mdx
  product_docs/docs/ocl_connector/15/06_using_ssl.mdx
  product_docs/docs/ocl_connector/15/07_scram_compatibility.mdx
  product_docs/docs/ocl_connector/15/installing/windows.mdx
Labels: deploy

#4732 Close admonition, correct path
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_sql_tutorial/01_sample_database/01_sample_database_installation.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_sql_tutorial/08_deletions.mdx
Labels: deploy

#4736 BigAnimal: spell out SLA for clarity
  product_docs/docs/biganimal/release/overview/02_high_availability.mdx
Labels: deploy

#4722 BigAnimal: pooler language updates
  product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
  product_docs/docs/biganimal/release/knowledge_base.mdx
  product_docs/docs/biganimal/release/overview/extensions_tools.mdx
  product_docs/docs/biganimal/release/overview/poolers.mdx
Labels: deploy

#4726 Move online help redirects to PEM 9
  product_docs/docs/pem/8/considerations/pem_pgbouncer/configuring_pgBouncer.mdx
  product_docs/docs/pem/9/considerations/pem_pgbouncer/configuring_pgBouncer.mdx
  product_docs/docs/pem/9/considerations/pem_pgbouncer/configuring_the_pem_agent.mdx
  product_docs/docs/pem/9/considerations/pem_pgbouncer/index.mdx
  product_docs/docs/pem/9/considerations/pem_pgbouncer/pem_server_pem_agent_connection_management_mechanism.mdx
  product_docs/docs/pem/9/considerations/pem_pgbouncer/preparing_the_pem_database_server.mdx
Labels: deploy
