Repository EnterpriseDB/docs, pull requests merged in 2023-07, with the labels that each got.

#4313 PEM - 9.2.1 release branch
  product_docs/docs/pem/9/pem_rel_notes/921_rel_notes.mdx
  product_docs/docs/pem/9/pem_rel_notes/index.mdx
Labels: deploy

#4327 docs: Adding BigAnimal GCP customizing compliance page
  product_docs/docs/biganimal/release/administering_cluster/customizing_compliance/gcp_policy_definitions.mdx
Labels: deploy

#4262 Wait States: standalone doc
  advocacy_docs/pg_extensions/wait_states/index.mdx
  advocacy_docs/pg_extensions/wait_states/installing.mdx
  advocacy_docs/pg_extensions/wait_states/using.mdx
  build-sources.json
  gatsby-config.js
  product_docs/docs/epas/15/managing_performance/evaluating_wait_states.mdx
  src/constants/products.js
  src/pages/index.js
Labels: deploy

#4315 .Net connector - 7.0.4.1 release branch
  product_docs/docs/net_connector/7.0.4.1/01_release_notes.mdx
  product_docs/docs/net_connector/7.0.4.1/02_requirements_overview.mdx
  product_docs/docs/net_connector/7.0.4.1/03_the_advanced_server_net_connector_overview.mdx
  product_docs/docs/net_connector/7.0.4.1/04_installing_and_configuring_the_net_connector.mdx
  product_docs/docs/net_connector/7.0.4.1/05_using_the_net_connector.mdx
  product_docs/docs/net_connector/7.0.4.1/06_opening_a_database_connection.mdx
  product_docs/docs/net_connector/7.0.4.1/07_retrieving_database_records.mdx
  product_docs/docs/net_connector/7.0.4.1/08_parameterized_queries.mdx
  product_docs/docs/net_connector/7.0.4.1/09_inserting_records_in_a_database.mdx
  product_docs/docs/net_connector/7.0.4.1/10_deleting_records_in_a_database.mdx
  product_docs/docs/net_connector/7.0.4.1/11_using_spl_stored_procedures_in_your_net_application.mdx
  product_docs/docs/net_connector/7.0.4.1/12_using_advanced_queueing.mdx
  product_docs/docs/net_connector/7.0.4.1/13_using_a_ref_cursor_in_a_net_application.mdx
  product_docs/docs/net_connector/7.0.4.1/14_using_plugins.mdx
  product_docs/docs/net_connector/7.0.4.1/15_using_object_types.mdx
  product_docs/docs/net_connector/7.0.4.1/16_scram_compatibility.mdx
  product_docs/docs/net_connector/7.0.4.1/17_advanced_server_net_connector_logging.mdx
  product_docs/docs/net_connector/7.0.4.1/18_api_reference.mdx
  product_docs/docs/net_connector/7.0.4.1/images/connection_opened_successfully.png
  product_docs/docs/net_connector/7.0.4.1/images/dialog.png
  product_docs/docs/net_connector/7.0.4.1/images/dotnet_installation_complete.png
  product_docs/docs/net_connector/7.0.4.1/images/dotnet_installation_dialog.png
  product_docs/docs/net_connector/7.0.4.1/images/dotnet_installation_wizard.png
  product_docs/docs/net_connector/7.0.4.1/images/ready_to_install.png
  product_docs/docs/net_connector/7.0.4.1/images/selecting_the_connectors_installer.png
  product_docs/docs/net_connector/7.0.4.1/images/starting_stackbuilder_plus.png
  product_docs/docs/net_connector/7.0.4.1/index.mdx
Labels: deploy

#4347 Added RHEL 9 to installing topics for PostgreSQL
  advocacy_docs/supported-open-source/postgresql/installing/index.mdx
  advocacy_docs/supported-open-source/postgresql/installing/linux_ppc64le/index.mdx
  advocacy_docs/supported-open-source/postgresql/installing/linux_ppc64le/postgresql_rhel_9.mdx
  advocacy_docs/supported-open-source/postgresql/installing/linux_x86_64/index.mdx
  advocacy_docs/supported-open-source/postgresql/installing/linux_x86_64/postgresql_other_linux_9.mdx
  advocacy_docs/supported-open-source/postgresql/installing/linux_x86_64/postgresql_rhel_9.mdx
  install_template/config.yaml
  install_template/templates/products/postgresql/almalinux-9-or-rocky-linux-9.njk
  install_template/templates/products/postgresql/rhel-9-or-ol-9.njk
  install_template/templates/products/postgresql/rhel-9_ppc64le.njk
Labels: deploy

#4030 TechPartner Thales CipherTrust Manager Guide
  advocacy_docs/partner_docs/HashicorpVault/05-UsingHashicorpVault.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/04-ConfiguringThalesCipherTrustManager.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/05-UsingThalesCipherTrustManager.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/07-SupportandLogging.mdx
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/AddKey.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/CreateNewRegistrationTokenCA.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/CreateNewRegistrationTokenCopyToken.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/CreateNewRegistrationTokenName.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/CreateNewRegistrationTokenSelectProfile.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/GeneratedKey.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/KeyDetails.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/KeyID.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/KeyMainPage.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/PYKMIPconffile.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/PartnerProgram.jpg.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/ThalesCheckKeys.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/ThalesCipherTrustAddUser.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/ThalesCipherTrustCACert.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/ThalesCipherTrustLoginScreen.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/ThalesCipherTrustManagerAddClientProfile.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/ThalesCipherTrustandEDBSolutionSummaryImage.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/ThalesDownloadCerts.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/ThalesRecords.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/ThalesRegistrationClient.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/Images/ThalesSolutionSummary.png
  advocacy_docs/partner_docs/ThalesCipherTrustManager/index.mdx
  src/pages/index.js
Labels: deploy

#4166 Tech Partner HPE Greenlake Guide
  advocacy_docs/partner_docs/HPE/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/HPE/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/HPE/04-ConfiguringHPEGreenlake.mdx
  advocacy_docs/partner_docs/HPE/05-UsingHPEGreenlake.mdx
  advocacy_docs/partner_docs/HPE/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/HPE/07-SupportandLogging.mdx
  advocacy_docs/partner_docs/HPE/Images/HPEDatabaseDisplay.png
  advocacy_docs/partner_docs/HPE/Images/HPESolutionSummaryImage.png
  advocacy_docs/partner_docs/HPE/Images/PartnerProgram.jpg.png
  advocacy_docs/partner_docs/HPE/Images/SampleDeployment.png
  advocacy_docs/partner_docs/HPE/index.mdx
  src/pages/index.js
Labels: deploy

#4043 TechPartner Hashicorp Vault Guide
  advocacy_docs/partner_docs/HashicorpVault/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/HashicorpVault/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/HashicorpVault/04-ConfiguringHashicorpVault.mdx
  advocacy_docs/partner_docs/HashicorpVault/05-UsingHashicorpVault.mdx
  advocacy_docs/partner_docs/HashicorpVault/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/HashicorpVault/07-SupportandLogging.mdx
  advocacy_docs/partner_docs/HashicorpVault/Images/HashicorpVaultSolutionSummaryImage.png
  advocacy_docs/partner_docs/HashicorpVault/Images/PartnerProgram.jpg.png
  advocacy_docs/partner_docs/HashicorpVault/index.mdx
  src/pages/index.js
Labels: deploy

#4228 Tech Partner Hashicorp Transit Secrets Engine Guide
  advocacy_docs/partner_docs/HashicorpVaultTransitSecretsEngine/02-PartnerInformation.mdx
  advocacy_docs/partner_docs/HashicorpVaultTransitSecretsEngine/03-SolutionSummary.mdx
  advocacy_docs/partner_docs/HashicorpVaultTransitSecretsEngine/04-ConfiguringTransitSecretsEngine.mdx
  advocacy_docs/partner_docs/HashicorpVaultTransitSecretsEngine/05-UsingTransitSecretsEngine.mdx
  advocacy_docs/partner_docs/HashicorpVaultTransitSecretsEngine/06-CertificationEnvironment.mdx
  advocacy_docs/partner_docs/HashicorpVaultTransitSecretsEngine/07-Support.mdx
  advocacy_docs/partner_docs/HashicorpVaultTransitSecretsEngine/Images/HashicorpVaultTransitSecretsEngineArchitecture(old).png
  advocacy_docs/partner_docs/HashicorpVaultTransitSecretsEngine/Images/HashicorpVaultTransitSecretsEngineArchitecture.png
  advocacy_docs/partner_docs/HashicorpVaultTransitSecretsEngine/Images/PartnerProgram.jpg.png
  advocacy_docs/partner_docs/HashicorpVaultTransitSecretsEngine/index.mdx
  src/pages/index.js
Labels: deploy

#4371 .NET Connector: updates to examples
  product_docs/docs/net_connector/7.0.4.1/06_opening_a_database_connection.mdx
  product_docs/docs/net_connector/7.0.4.1/07_retrieving_database_records.mdx
  product_docs/docs/net_connector/7.0.4.1/08_parameterized_queries.mdx
  product_docs/docs/net_connector/7.0.4.1/09_inserting_records_in_a_database.mdx
  product_docs/docs/net_connector/7.0.4.1/10_deleting_records_in_a_database.mdx
  product_docs/docs/net_connector/7.0.4.1/11_using_spl_stored_procedures_in_your_net_application.mdx
  product_docs/docs/net_connector/7.0.4.1/13_using_a_ref_cursor_in_a_net_application.mdx
Labels: deploy

#4352 Initial import of Lasso docs
  build-sources.json
  gatsby-config.js
  product_docs/docs/lasso/4/appendix-a.mdx
  product_docs/docs/lasso/4/collected-data.mdx
  product_docs/docs/lasso/4/common.mdx
  product_docs/docs/lasso/4/describe.mdx
  product_docs/docs/lasso/4/download.mdx
  product_docs/docs/lasso/4/index.mdx
  product_docs/docs/lasso/4/linux.mdx
  product_docs/docs/lasso/4/return.mdx
  product_docs/docs/lasso/4/supervised.mdx
  product_docs/docs/lasso/4/troubleshooting.mdx
  product_docs/docs/lasso/4/unsupervised.mdx
  product_docs/docs/lasso/4/windows.mdx
  src/constants/products.js
  src/pages/index.js
Labels: deploy

#4390 Extensions: index page updates
  advocacy_docs/pg_extensions/extensionrefs.json
  advocacy_docs/pg_extensions/index.mdx
  advocacy_docs/pg_extensions/index.mdx.in
Labels: deploy

#4385 EPAS - 15 SQL reference re-org
  product_docs/docs/epas/15/application_programming/epas_compat_spl/02_spl_programs/07_subprograms_subprocedures_and_subfunctions/06_overloading_subprograms.mdx
  product_docs/docs/epas/15/fundamentals/epas_fundamentals/epas_compat_ora_dev_guide/index.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_sql_tutorial/09_the_sql_language.mdx
  product_docs/docs/epas/15/index.mdx
  product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_sql/34_create_sequence.mdx
  product_docs/docs/epas/15/reference/oracle_compatibility_reference/epas_compat_sql/36_create_table.mdx
  product_docs/docs/epas/15/reference/sql_reference/01_sql_syntax/01_lexical_structure.mdx
  product_docs/docs/epas/15/reference/sql_reference/01_sql_syntax/02_identifiers_and_key_words.mdx
  product_docs/docs/epas/15/reference/sql_reference/01_sql_syntax/03_constants.mdx
  product_docs/docs/epas/15/reference/sql_reference/01_sql_syntax/04_comments.mdx
  product_docs/docs/epas/15/reference/sql_reference/01_sql_syntax/index.mdx
  product_docs/docs/epas/15/reference/sql_reference/02_data_types/01_numeric_types.mdx
  product_docs/docs/epas/15/reference/sql_reference/02_data_types/02_character_types.mdx
  product_docs/docs/epas/15/reference/sql_reference/02_data_types/03_binary_data.mdx
  product_docs/docs/epas/15/reference/sql_reference/02_data_types/04_date_time_types.mdx
  product_docs/docs/epas/15/reference/sql_reference/02_data_types/05_boolean_type.mdx
  product_docs/docs/epas/15/reference/sql_reference/02_data_types/06_xml_type.mdx
  product_docs/docs/epas/15/reference/sql_reference/02_data_types/index.mdx
  product_docs/docs/epas/15/reference/sql_reference/02_the_sql_language/index.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/01_logical_operators.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/02_comparison_operators.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/03_mathematical_functions_and_operators.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/04_string_functions_and_operators.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/05_pattern_matching_string_functions.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/06_pattern_matching_using_the_like_operator.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/07_data_type_formatting_functions.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/08_date_time_functions_and_operators.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/09_sequence_manipulation_functions.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/10_conditional_expressions.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/11_aggregate_functions.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/12_subquery_expressions.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/13_identifier_functions.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/14_bitwise_functions.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/index.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/to_multi_byte.mdx
  product_docs/docs/epas/15/reference/sql_reference/03_functions_and_operators/to_single_byte.mdx
  product_docs/docs/epas/15/reference/sql_reference/index.mdx
Labels: deploy

#4372 PEM: Managing PEM agent topic reorg
  product_docs/docs/pem/9/managing_pem_agent.mdx
  product_docs/docs/pem/9/managing_pem_agent/index.mdx
  product_docs/docs/pem/9/managing_pem_agent/managing_job_notifications.mdx
  product_docs/docs/pem/9/managing_pem_agent/managing_scheduled_jobs.mdx
  product_docs/docs/pem/9/managing_pem_agent/modifying_agent_configuration.mdx
  product_docs/docs/pem/9/managing_pem_agent/modifying_agent_properties.mdx
  product_docs/docs/pem/9/managing_pem_agent/setting_agent_privileges.mdx
Labels: deploy

#4356 BDR-3735 - Add release notes for HARP 2.3.0
  product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.3.0_rel_notes.mdx
  product_docs/docs/pgd/3.7/harp/01_release_notes/index.mdx
  product_docs/docs/pgd/4/rel_notes/index.mdx
  product_docs/docs/pgd/4/rel_notes/pgd_4.3.1_rel_notes.mdx
Labels: upcoming-release

#4186 BDR-3497 document harp probes
  product_docs/docs/pgd/3.7/harp/02_overview.mdx
  product_docs/docs/pgd/3.7/harp/04_configuration.mdx
  product_docs/docs/pgd/4/harp/04_configuration.mdx
  product_docs/docs/pgd/4/harp/index.mdx
Labels: upcoming-release

#4368 Added note on TDE presence check
  product_docs/docs/tde/15/enabling_tde.mdx
Labels: deploy

#4391 Edits to EDB .Net doc
  product_docs/docs/net_connector/7.0.4.1/03_the_advanced_server_net_connector_overview.mdx
  product_docs/docs/net_connector/7.0.4.1/04_installing_and_configuring_the_net_connector.mdx
  product_docs/docs/net_connector/7.0.4.1/06_opening_a_database_connection.mdx
  product_docs/docs/net_connector/7.0.4.1/07_retrieving_database_records.mdx
  product_docs/docs/net_connector/7.0.4.1/10_deleting_records_in_a_database.mdx
  product_docs/docs/net_connector/7.0.4.1/11_using_spl_stored_procedures_in_your_net_application.mdx
  product_docs/docs/net_connector/7.0.4.1/12_using_advanced_queueing.mdx
  product_docs/docs/net_connector/7.0.4.1/13_using_a_ref_cursor_in_a_net_application.mdx
  product_docs/docs/net_connector/7.0.4.1/14_using_plugins.mdx
  product_docs/docs/net_connector/7.0.4.1/15_using_object_types.mdx
  product_docs/docs/net_connector/7.0.4.1/16_scram_compatibility.mdx
  product_docs/docs/net_connector/7.0.4.1/17_advanced_server_net_connector_logging.mdx
  product_docs/docs/net_connector/7.0.4.1/index.mdx
Labels: deploy

#4420 Update key_stores.mdx
  product_docs/docs/tde/15/key_stores.mdx
Labels: deploy

#4413 Doc/fix/updatepgd4releasenotes
  product_docs/docs/pgd/4/rel_notes/index.mdx
  product_docs/docs/pgd/4/rel_notes/pgd_4.3.0-1_rel_notes.mdx
  product_docs/docs/pgd/4/rel_notes/pgd_4.3.0_rel_notes.mdx
  product_docs/docs/pgd/4/rel_notes/pgd_4.3.1-1_rel_notes.mdx
  product_docs/docs/pgd/4/rel_notes/pgd_4.3.1_rel_notes.mdx
Labels: deploy

#4400 Updated headlines for July
  src/pages/index.js
Labels: deploy

#4345 PEM - Upgrade topics
  product_docs/docs/pem/9/upgrading/upgrading_pem_installation/upgrading_pem_installation_linux_rpm.mdx
Labels: deploy

#4286 Update column-level-conflicts.mdx
  product_docs/docs/pgd/5/consistency/column-level-conflicts.mdx
Labels: deploy

#4428 PEM - 9.2.2 and 8.6.3 release
  product_docs/docs/pem/8/pem_rel_notes/863_rel_notes.mdx
  product_docs/docs/pem/8/pem_rel_notes/index.mdx
  product_docs/docs/pem/9/pem_rel_notes/922_rel_notes.mdx
  product_docs/docs/pem/9/pem_rel_notes/index.mdx
Labels: deploy

#4430 Added archive page
  product_docs/docs/tpa/23/rel_notes/index.mdx
  product_docs/docs/tpa/23/rel_notes/tpa_23.1-11_rel_notes.mdx
Labels: deploy

#4435 PEM - 9.2.2 and 8.6.3 release notes update
  product_docs/docs/pem/8/pem_rel_notes/index.mdx
  product_docs/docs/pem/9/pem_rel_notes/index.mdx
Labels: deploy

#4432 BigAnimal: Creating a cluster hierarchy fix
  product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
Labels: deploy

#4312 TDE: performance
  product_docs/docs/tde/15/index.mdx
Labels: deploy

#4348 cookbook for adding new platform
  install_template/README.md
Labels: deploy

#4426 NET connector - added EDBDataSource to overview section
  product_docs/docs/net_connector/7.0.4.1/03_the_advanced_server_net_connector_overview.mdx
Labels: deploy

#4416 EPAS reorg: Phase 2 Security branch topic restructure
  product_docs/docs/epas/15/epas_security_guide/02_protecting_against_sql_injection_attacks/02_configuring_sql_protect.mdx
  product_docs/docs/epas/15/epas_security_guide/03_edb_wrap/edb_wrap_key_concepts.mdx
  product_docs/docs/epas/15/epas_security_guide/03_edb_wrap/index.mdx
  product_docs/docs/epas/15/epas_security_guide/03_edb_wrap/obfuscating_source_code.mdx
  product_docs/docs/epas/15/epas_security_guide/04_profile_management/profile_overview.mdx
  product_docs/docs/epas/15/epas_security_guide/05_data_redaction.mdx
  product_docs/docs/epas/15/epas_security_guide/05_data_redaction/creating_a_data_redaction_policy.mdx
  product_docs/docs/epas/15/epas_security_guide/05_data_redaction/data_redaction_key_concepts.mdx
  product_docs/docs/epas/15/epas_security_guide/05_data_redaction/data_redaction_system_catalogs.mdx
  product_docs/docs/epas/15/epas_security_guide/05_data_redaction/index.mdx
  product_docs/docs/epas/15/epas_security_guide/05_data_redaction/modifying_a_data_redaction_policy.mdx
  product_docs/docs/epas/15/epas_security_guide/05_data_redaction/removing_a_data_redaction_policy.mdx
  product_docs/docs/epas/15/epas_security_guide/05_edb_audit_logging/01_audit_logging_configuration_parameters.mdx
  product_docs/docs/epas/15/epas_security_guide/05_edb_audit_logging/02_selecting_sql_statements_to_audit.mdx
  product_docs/docs/epas/15/epas_security_guide/05_edb_audit_logging/04_audit_log_file.mdx
  product_docs/docs/epas/15/epas_security_guide/05_edb_audit_logging/08_audit_log_archiving.mdx
  product_docs/docs/epas/15/epas_security_guide/05_edb_audit_logging/index.mdx
Labels: deploy

#4421 EPAS reorg: Phase 2 Application programming branch topic restructure
  product_docs/docs/epas/15/application_programming/12_debugger.mdx
  product_docs/docs/epas/15/application_programming/12_debugger/configuring_debugger.mdx
  product_docs/docs/epas/15/application_programming/12_debugger/debugger_interface.mdx
  product_docs/docs/epas/15/application_programming/12_debugger/debugging_a_program.mdx
  product_docs/docs/epas/15/application_programming/12_debugger/index.mdx
  product_docs/docs/epas/15/application_programming/12_debugger/starting_debugger.mdx
  product_docs/docs/epas/15/application_programming/15_enhanced_sql_and_other_misc_features/comment_command.mdx
  product_docs/docs/epas/15/application_programming/15_enhanced_sql_and_other_misc_features/index.mdx
  product_docs/docs/epas/15/application_programming/15_enhanced_sql_and_other_misc_features/logical_decoding.mdx
  product_docs/docs/epas/15/application_programming/15_enhanced_sql_and_other_misc_features/obtaining_version_information.mdx
  product_docs/docs/epas/15/application_programming/ecpgplus_guide/05_building_executing_dynamic_sql_statements.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_table_partitioning/05_handling_stray_values_in_a_list_or_range_partitioned_table/defining_a_default_partition.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_table_partitioning/05_handling_stray_values_in_a_list_or_range_partitioned_table/defining_a_maxvalue_partition.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_table_partitioning/05_handling_stray_values_in_a_list_or_range_partitioned_table/index.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_table_partitioning/06_specifying_multiple_partitioning_keys_in_a_range_partitioned_table.mdx
  product_docs/docs/epas/15/managing_performance/04_dynamic_runtime_instrumentation_tools_architecture_DRITA/index.mdx
  product_docs/docs/epas/15/managing_performance/04_dynamic_runtime_instrumentation_tools_architecture_DRITA/performance_tuning_recommendations.mdx
  product_docs/docs/epas/15/managing_performance/04_dynamic_runtime_instrumentation_tools_architecture_DRITA/simulating_statspack_reports.mdx
  product_docs/docs/epas/15/managing_performance/04_dynamic_runtime_instrumentation_tools_architecture_DRITA/taking_a_snapshot.mdx
  product_docs/docs/epas/15/managing_performance/04_dynamic_runtime_instrumentation_tools_architecture_DRITA/using_drita_functions.mdx
Labels: deploy

#4443 Partner docs: restoring Security section on home page
  src/pages/index.js
Labels: deploy

#4454 Home page: moved Migration block back to the top
  src/pages/index.js
Labels: deploy

#4459 Fix bad link to index
  product_docs/docs/pgd/4/harp/04_configuration.mdx
Labels: deploy

#4471 Add option to have PREVIEW in the cells
  advocacy_docs/pg_extensions/extensionrefs.json
  advocacy_docs/pg_extensions/index.mdx
  tools/user/import/extensions/exsp.js
Labels: deploy

#4472 BigAnimal: new diagrams
  product_docs/docs/biganimal/release/overview/02_high_availability.mdx
  product_docs/docs/biganimal/release/overview/images/extreme-high-availability-3-regions.png
  product_docs/docs/biganimal/release/overview/images/extreme-high-availability-3-regions.svg
  product_docs/docs/biganimal/release/overview/images/extreme-high-availability-single-region.png
  product_docs/docs/biganimal/release/overview/images/extreme-high-availability-single-region.svg
  product_docs/docs/biganimal/release/overview/images/high-availability-old.png
  product_docs/docs/biganimal/release/overview/images/high-availability.png
  product_docs/docs/biganimal/release/overview/images/high-availability.svg
  product_docs/docs/biganimal/release/overview/images/single-node.png
  product_docs/docs/biganimal/release/overview/images/single-node.svg
Labels: deploy

#4223 Add Patroni quick-starts step numbers
  advocacy_docs/supported-open-source/patroni/debian11_quick_start.mdx
  advocacy_docs/supported-open-source/patroni/installing_patroni.mdx
  advocacy_docs/supported-open-source/patroni/rhel8_quick_start.mdx
  advocacy_docs/supported-open-source/patroni/tips.mdx
Labels: deploy

#4483 Add Patroni bin_name setting
  advocacy_docs/supported-open-source/patroni/debian11_quick_start.mdx
  advocacy_docs/supported-open-source/patroni/rhel8_quick_start.mdx
Labels: deploy

#4510 Explicit 2PC usage w/ CAMO/Eager/GC is a limitation
  product_docs/docs/pgd/4/known_issues.mdx
  product_docs/docs/pgd/4/limitations.mdx
  product_docs/docs/pgd/5/known_issues.mdx
  product_docs/docs/pgd/5/limitations.mdx
Labels: upcoming-release

#4494 EPAS: Switching absolute links to relative links
  product_docs/docs/epas/15/application_programming/epas_compat_spl/14_packages.mdx
  product_docs/docs/epas/15/application_programming/epas_compat_table_partitioning/05_handling_stray_values_in_a_list_or_range_partitioned_table/defining_a_maxvalue_partition.mdx
  product_docs/docs/epas/15/application_programming/optimizing_code/optimizing_code.mdx
  product_docs/docs/epas/15/database_administration/01_configuration_parameters/03_configuration_parameters_by_functionality/08_ccd_locale_and_formatting.mdx
  product_docs/docs/epas/15/database_administration/01_configuration_parameters/03_configuration_parameters_by_functionality/09_ccd_statement_behaviour.mdx
  product_docs/docs/epas/15/database_administration/01_configuration_parameters/03_configuration_parameters_by_functionality/12_customized_options.mdx
  product_docs/docs/epas/15/database_administration/01_configuration_parameters/03_configuration_parameters_by_functionality/index.mdx
  product_docs/docs/epas/15/database_administration/02_edb_loader/building_the_control_file/index.mdx
  product_docs/docs/epas/15/database_administration/02_edb_loader/invoking_edb_loader/conventional_path_load.mdx
  product_docs/docs/epas/15/database_administration/02_edb_loader/invoking_edb_loader/index.mdx
  product_docs/docs/epas/15/database_administration/02_edb_loader/invoking_edb_loader/performing_remote_loading.mdx
  product_docs/docs/epas/15/fundamentals/epas_fundamentals/benefits_epas.mdx
  product_docs/docs/epas/15/fundamentals/epas_fundamentals/epas_compat_ora_dev_guide/index.mdx
  product_docs/docs/epas/15/fundamentals/sql_fundamentals/02_sql_tutorial/09_the_sql_language.mdx
  product_docs/docs/epas/15/index.mdx
  product_docs/docs/epas/15/installing/linux_install_details/rpm_packages.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/index.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/invoking_the_graphical_installer_from_the_command_line/reference_command_line_options.mdx
  product_docs/docs/epas/15/installing/windows/installing_advanced_server_with_the_interactive_installer/performing_a_graphical_installation_on_windows.mdx
  product_docs/docs/epas/15/planning/configuration_mode.mdx
  product_docs/docs/epas/15/planning/deployment_options/index.mdx
  product_docs/docs/epas/15/reference/oracle_compatibility_reference/summary_oracle_config_parameters.mdx
  product_docs/docs/epas/15/tools_utilities_and_components/application_developer_tools/10_ecpgplus.mdx
  product_docs/docs/epas/15/tools_utilities_and_components/database_administration_tools/09_tools_and_utilities.mdx
  product_docs/docs/epas/15/tools_utilities_and_components/database_administration_tools/edb_clone_schema_overview.mdx
  product_docs/docs/epas/15/tools_utilities_and_components/database_administration_tools/edb_loader_overview.mdx
  product_docs/docs/epas/15/tools_utilities_and_components/database_administration_tools/edb_resource_manager_overview.mdx
  product_docs/docs/epas/15/upgrading/04_upgrading_an_installation_with_pg_upgrade/index.mdx
  product_docs/docs/epas/15/working_with_oracle_data/02_enhanced_compatibility_features.mdx
  product_docs/docs/epas/15/working_with_oracle_data/07_open_client_library.mdx
  product_docs/docs/epas/15/working_with_oracle_data/embedded_sql_commands.mdx
  product_docs/docs/epas/15/working_with_oracle_data/loading_bulk_data.mdx
  product_docs/docs/epas/15/working_with_oracle_data/proprietary_source_code.mdx
  product_docs/docs/hadoop_data_adapter/2/10b_example_aggregate_pushdown.mdx
Labels: deploy

#4497 BDR-3768 - Add release notes for HARP 2.3.1
  product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.3.1_rel_notes.mdx
  product_docs/docs/pgd/3.7/harp/01_release_notes/index.mdx
  product_docs/docs/pgd/4/rel_notes/index.mdx
  product_docs/docs/pgd/4/rel_notes/pgd_4.3.1-2_rel_notes.mdx
Labels: upcoming-release

#4518 Doc/fix - crop issue rel note
  product_docs/docs/pgd/3.7/harp/01_release_notes/harp2.3.1_rel_notes.mdx
  product_docs/docs/pgd/4/rel_notes/pgd_4.3.1-2_rel_notes.mdx
Labels: deploy

#4513 BigAnimal: Q2 extensions
  product_docs/docs/biganimal/release/overview/extensions_tools.mdx
Labels: deploy

#4533 Process changes to docs from: repo: EnterpriseDB/cloud-native-postgres ref: refs/tags/v1.20.2
  product_docs/docs/postgres_for_kubernetes/1/api_reference.mdx
  product_docs/docs/postgres_for_kubernetes/1/bootstrap.mdx
  product_docs/docs/postgres_for_kubernetes/1/index.mdx
  product_docs/docs/postgres_for_kubernetes/1/installation_upgrade.mdx
  product_docs/docs/postgres_for_kubernetes/1/interactive_demo.mdx
  product_docs/docs/postgres_for_kubernetes/1/openshift.mdx
  product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_18_6_rel_notes.mdx
  product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_19_4_rel_notes.mdx
  product_docs/docs/postgres_for_kubernetes/1/rel_notes/1_20_2_rel_notes.mdx
  product_docs/docs/postgres_for_kubernetes/1/rel_notes/index.mdx
  product_docs/docs/postgres_for_kubernetes/1/troubleshooting.mdx
Labels: deploy

#4521 Document how to migrate an existing Postgres cluster to a Patroni managed cluster.
  advocacy_docs/supported-open-source/patroni/index.mdx
  advocacy_docs/supported-open-source/patroni/migrating.mdx
Labels: documentation, deploy

#4540 Added link in OTEL to SQL info
  product_docs/docs/pgd/5/monitoring/otel.mdx
Labels: deploy
