Repository EnterpriseDB/docs, pull requests merged in 2023-05, with the labels that each got.

#4000 BigAnimal: add PGD Proxy info
  product_docs/docs/biganimal/release/overview/02_high_availability.mdx
Labels: deploy

#4011 BigAnimal: added link to PGD docs from PGD Proxy para
  product_docs/docs/biganimal/release/overview/02_high_availability.mdx
Labels: deploy

#4017 Update index.mdx
  product_docs/docs/eprs/7/index.mdx
Labels: deploy

#3577 BigAnimal: prototype for new regions format
  product_docs/docs/biganimal/release/overview/03a_region_support.mdx
  product_docs/docs/biganimal/release/overview/03a_region_support/country_reference.mdx
  product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
Labels: deploy

#4033 BigAnimal: linking to Oracles dbs
  product_docs/docs/biganimal/release/knowledge_base.mdx
  product_docs/docs/biganimal/release/migration/index.mdx
Labels: deploy

#4039 EPAS - 11 to 14 SQL Profiler and Index Advisor updates
  product_docs/docs/epas/11/epas_guide/03_database_administration/02_index_advisor/01_index_advisor_components.mdx
  product_docs/docs/epas/11/epas_guide/03_database_administration/02_index_advisor/02_index_advisor_configuration.mdx
  product_docs/docs/epas/11/epas_guide/03_database_administration/02_index_advisor/index.mdx
  product_docs/docs/epas/11/epas_guide/03_database_administration/03_sql_profiler.mdx
  product_docs/docs/epas/12/epas_guide/03_database_administration/02_index_advisor/01_index_advisor_components.mdx
  product_docs/docs/epas/12/epas_guide/03_database_administration/02_index_advisor/02_index_advisor_configuration.mdx
  product_docs/docs/epas/12/epas_guide/03_database_administration/02_index_advisor/index.mdx
  product_docs/docs/epas/12/epas_guide/03_database_administration/03_sql_profiler.mdx
  product_docs/docs/epas/13/epas_guide/03_database_administration/02_index_advisor/01_index_advisor_components.mdx
  product_docs/docs/epas/13/epas_guide/03_database_administration/02_index_advisor/02_index_advisor_configuration.mdx
  product_docs/docs/epas/13/epas_guide/03_database_administration/02_index_advisor/index.mdx
  product_docs/docs/epas/13/epas_guide/03_database_administration/03_sql_profiler.mdx
  product_docs/docs/epas/14/epas_guide/03_database_administration/02_index_advisor/01_index_advisor_components.mdx
  product_docs/docs/epas/14/epas_guide/03_database_administration/02_index_advisor/02_index_advisor_configuration.mdx
  product_docs/docs/epas/14/epas_guide/03_database_administration/02_index_advisor/index.mdx
  product_docs/docs/epas/14/epas_guide/03_database_administration/03_sql_profiler.mdx
Labels: deploy

#3714 BigAnimal: PgBouncer option
  product_docs/docs/biganimal/release/getting_started/creating_a_cluster/index.mdx
  product_docs/docs/biganimal/release/knowledge_base.mdx
  product_docs/docs/biganimal/release/overview/extensions_tools.mdx
  product_docs/docs/biganimal/release/pricing_and_billing/index.mdx
  product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/index.mdx
  product_docs/docs/biganimal/release/using_cluster/02_connecting_your_cluster/pgbouncer_configuring.mdx
  product_docs/docs/biganimal/release/using_cluster/03_modifying_your_cluster/index.mdx
Labels: deploy

#4051 Changes quickstart for 23.17 --pgd-proxy-routing
  product_docs/docs/pgd/5/quickstart/quick_start_aws.mdx
  product_docs/docs/pgd/5/quickstart/quick_start_docker.mdx
  product_docs/docs/pgd/5/quickstart/quick_start_linux.mdx
  product_docs/docs/pgd/5/tpa.mdx
Labels: deploy

#4047 TDE: updates
  product_docs/docs/tde/15/key_stores.mdx
Labels: deploy

#4050 EPAS - 11 to 15 release notes
  product_docs/docs/epas/11/epas_rel_notes/epas11_20_31_rel_notes.mdx
  product_docs/docs/epas/11/epas_rel_notes/index.mdx
  product_docs/docs/epas/12/epas_rel_notes/epas12_15_19_rel_notes.mdx
  product_docs/docs/epas/12/epas_rel_notes/index.mdx
  product_docs/docs/epas/13/epas_rel_notes/epas13_11_15_rel_notes.mdx
  product_docs/docs/epas/13/epas_rel_notes/index.mdx
  product_docs/docs/epas/14/epas_rel_notes/epas14_8_0_rel_notes.mdx
  product_docs/docs/epas/14/epas_rel_notes/index.mdx
  product_docs/docs/epas/15/epas_rel_notes/epas15_3_0_rel_notes.mdx
  product_docs/docs/epas/15/epas_rel_notes/index.mdx
Labels: deploy

#4064 Changes to introduce write leader
  product_docs/docs/pgd/5/overview/index.mdx
  product_docs/docs/pgd/5/terminology.mdx
Labels: deploy

#4068 Import TPA 23.17 Updates
  product_docs/docs/tpa/23/INSTALL.mdx
  product_docs/docs/tpa/23/architecture-BDR-Always-ON.mdx
  product_docs/docs/tpa/23/architecture-M1.mdx
  product_docs/docs/tpa/23/architecture-PGD-Always-ON.mdx
  product_docs/docs/tpa/23/configure-instance.mdx
  product_docs/docs/tpa/23/configure-source.mdx
  product_docs/docs/tpa/23/index.mdx
  product_docs/docs/tpa/23/misc-troubleshooting.mdx
  product_docs/docs/tpa/23/platform-aws.mdx
  product_docs/docs/tpa/23/platform-bare.mdx
  product_docs/docs/tpa/23/reference/air-gapped.mdx
  product_docs/docs/tpa/23/reference/bdr.mdx
  product_docs/docs/tpa/23/reference/distributions.mdx
  product_docs/docs/tpa/23/reference/harp.mdx
  product_docs/docs/tpa/23/reference/local-repo.mdx
  product_docs/docs/tpa/23/reference/locale.mdx
  product_docs/docs/tpa/23/reference/pgd-proxy.mdx
  product_docs/docs/tpa/23/reference/pglogical.mdx
  product_docs/docs/tpa/23/reference/repmgr.mdx
  product_docs/docs/tpa/23/reference/tpaexec-support.mdx
  product_docs/docs/tpa/23/reference/yum_repositories.mdx
  product_docs/docs/tpa/23/tpaexec-configure.mdx
  product_docs/docs/tpa/23/tpaexec-hooks.mdx
  product_docs/docs/tpa/23/tpaexec-server-pool.mdx
  product_docs/docs/tpa/23/tpaexec-switchover.mdx
  product_docs/docs/tpa/23/tpaexec-update-postgres.mdx
Labels: deploy

#4055 MySQL FDW: Platform Support Updates
  product_docs/docs/mysql_data_adapter/2/02_requirements_overview.mdx
Labels: deploy

#4074 Postgres Distributed for Kubernetes preview release 0.6
  build-sources.json
  gatsby-config.js
  product_docs/docs/postgres_distributed_for_kubernetes/1/api_reference.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/architecture.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/connectivity.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/images/openshift/all-namespaces.png
  product_docs/docs/postgres_distributed_for_kubernetes/1/images/openshift/find-pgd-openshift.png
  product_docs/docs/postgres_distributed_for_kubernetes/1/images/openshift/operatorhub_1.png
  product_docs/docs/postgres_distributed_for_kubernetes/1/images/pg4k-pgd-basic-architecture.png
  product_docs/docs/postgres_distributed_for_kubernetes/1/index.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/installation_upgrade.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/quickstart.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/rel_notes/0_6_rel_notes.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/rel_notes/index.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/samples.mdx
  product_docs/docs/postgres_distributed_for_kubernetes/1/samples/flexible_3regions.yaml
  product_docs/docs/postgres_distributed_for_kubernetes/1/samples/flexible_cleanup.yaml
  scripts/source/dispatch_product.py
  scripts/source/process-pgd4k-docs.sh
  src/constants/products.js
  src/templates/doc.js
Labels: deploy

#4071 EPAS - 12 to 15 removed edb_custom_plan_tries as per DF-335
  product_docs/docs/epas/12/epas_guide/03_database_administration/01_configuration_parameters/02_summary_of_configuration_parameters.mdx
  product_docs/docs/epas/12/epas_rel_notes/19_epas12.1.2_rel_notes.mdx
  product_docs/docs/epas/13/epas_guide/03_database_administration/01_configuration_parameters/02_summary_of_configuration_parameters.mdx
  product_docs/docs/epas/14/epas_guide/03_database_administration/01_configuration_parameters/02_summary_of_configuration_parameters.mdx
  product_docs/docs/epas/15/epas_guide/03_database_administration/01_configuration_parameters/02_summary_of_configuration_parameters.mdx
Labels: deploy

#4077 Doc/update/tpa23.17update
  product_docs/docs/tpa/23/INSTALL.mdx
  product_docs/docs/tpa/23/architecture-BDR-Always-ON.mdx
  product_docs/docs/tpa/23/architecture-M1.mdx
  product_docs/docs/tpa/23/architecture-PGD-Always-ON.mdx
  product_docs/docs/tpa/23/configure-cluster.mdx
  product_docs/docs/tpa/23/configure-instance.mdx
  product_docs/docs/tpa/23/reference/distributions.mdx
  product_docs/docs/tpa/23/tpaexec-provision.mdx
  scripts/source/process-tpa-docs-auto.sh
  scripts/source/tpaexec.js
Labels: deploy

#4072 Migration Portal: v4.5 release
  product_docs/docs/migration_portal/4/01_mp_release_notes/index.mdx
  product_docs/docs/migration_portal/4/01_mp_release_notes/mp_4.5_rel_notes.mdx
  product_docs/docs/migration_portal/4/04_mp_migrating_database/01_mp_schema_extraction/index.mdx
  product_docs/docs/migration_portal/4/known_issues_notes.mdx
Labels: deploy

#4076 EPAS 15 - Update NVL function as per DB-2274
  product_docs/docs/epas/15/epas_compat_reference/02_the_sql_language/03_functions_and_operators/10_conditional_expressions.mdx
  product_docs/docs/epas/15/epas_rel_notes/epas15_2_0_rel_notes.mdx
Labels: deploy

#3976 PGD 5.1: Add bdr.drop_node_group docs
  product_docs/docs/pgd/5/nodes.mdx
Labels: upcoming-release

#4109 BigAnimal: faraway clusters replication lag
  product_docs/docs/biganimal/release/overview/replication.mdx
  product_docs/docs/biganimal/release/using_cluster/04_backup_and_restore.mdx
Labels: deploy

#4114 PEM - 9.2 Release branch
  product_docs/docs/pem/9/pem_rel_notes/920_rel_notes.mdx
  product_docs/docs/pem/9/pem_rel_notes/index.mdx
Labels: deploy

#4126 Fixing links in BigAnimal and PGD
  product_docs/docs/biganimal/release/overview/replication.mdx
  product_docs/docs/pgd/5/routing/proxy.mdx
Labels: deploy

#3845 Replication Server: v7.5.1 release
  product_docs/docs/eprs/7/02_overview/03_replication_server_components_and_architecture/01_physical_components.mdx
  product_docs/docs/eprs/7/05_smr_operation/01_prerequisites/01_setting_heap_size_for_pub_and_sub.mdx
  product_docs/docs/eprs/7/05_smr_operation/01_prerequisites/06_verifying_host_accessibility.mdx
  product_docs/docs/eprs/7/05_smr_operation/04_on_demand_replication/01_perform_replication.mdx
  product_docs/docs/eprs/7/06_mmr_operation/05_on_demand_replication_mmr.mdx
  product_docs/docs/eprs/7/07_common_operations/05_managing_history.mdx
  product_docs/docs/eprs/7/08_xdb_cli/01_prereq_steps.mdx
  product_docs/docs/eprs/7/10_appendix/02_resolving_problems/04_troubleshooting_areas.mdx
  product_docs/docs/eprs/7/eprs_rel_notes/eprs_rel_notes_7.5.1.mdx
  product_docs/docs/eprs/7/eprs_rel_notes/index.mdx
Labels: upcoming-release, deploy

#4123 Migration Toolkit: v55.6.0 release
  product_docs/docs/migration_toolkit/55/07_invoking_mtk/08_mtk_command_options.mdx
  product_docs/docs/migration_toolkit/55/mtk_rel_notes/index.mdx
  product_docs/docs/migration_toolkit/55/mtk_rel_notes/mtk_556_rel_notes.mdx
Labels: deploy

#4140 BigAnimal: ap-southeast-3 region
  product_docs/docs/biganimal/release/overview/03a_region_support/index.mdx
Labels: upcoming-release, deploy

#4147 TDE: replacing ascii code with the correct characters
  product_docs/docs/tde/15/key_stores.mdx
Labels: deploy

#4138 Nav bar usability enhancements
  gatsby-browser.js
  gatsby-config.js
  product_docs/docs/pgd/5/cli/command_ref/index.mdx
  product_docs/docs/pgd/5/cli/index.mdx
  product_docs/docs/pgd/5/consistency/index.mdx
  product_docs/docs/pgd/5/durability/index.mdx
  product_docs/docs/pgd/5/monitoring/index.mdx
  product_docs/docs/pgd/5/quickstart/index.mdx
  product_docs/docs/pgd/5/rel_notes/index.mdx
  product_docs/docs/pgd/5/routing/index.mdx
  product_docs/docs/pgd/5/upgrades/index.mdx
  src/components/side-navigation.js
  src/components/table-of-contents.js
  src/components/tree-node.js
  src/constants/gatsby-utils.js
  src/styles/_docs.scss
  src/styles/_overrides.scss
Labels: deploy
